#!/bin/sh
# Differential harness for application-processor start-up and adoption.
#
#   shim/            a stand-in hypervisor.h carrying only what the
#                    start-up path touches, plus this harness's own asm.h
#                    (CPUID has to answer) and vmx/asm.h (the VMCS has to
#                    be per thread - see the note in that file).
#   ../nested_vmx/shim
#                    zpp/diag/log.h, shared with the other harnesses.
#                    This directory comes first on the include path, so
#                    everything above wins and the rest falls through.
#   harness.cpp      the fake trampoline page, the fake targets and the
#                    tests.
#   real.cpp         generated below - the function bodies cut out of
#                    hypervisor.cpp, byte for byte.
#
# Cut by NAME, like tests/watched_page, and for the same reason:
# hypervisor.cpp is ten thousand lines and reaches the whole VMM, so the
# functions under test cannot be compiled by compiling the file. The cut
# moves with the code, and a renamed or deleted function fails the build
# here rather than silently testing nothing.
#
# Never run clang-format over this file. It reflows a shell script as C++
# and destroys it, exactly as CLAUDE.md records for Markdown.
set -e
cd "$(dirname "$0")"
SRC=${SRC:-"$(cd ../.. && pwd)/hypervisor"}

WANTED='processor_slot start_up_processor start_application_processor
        enter_root_mode'

{
    echo '// GENERATED by build.sh - do not edit, do not commit.'
    echo '// The bodies below are cut verbatim out of'
    echo '// hypervisor/src/hypervisor/hypervisor.cpp.'
    echo '#include "zpp/hypervisor/hypervisor.h"'
    echo 'namespace zpp::hypervisor {'
    awk -v wanted="$(echo $WANTED)" '
        BEGIN {
            split(wanted, names, " ");
            for (i in names) { want[names[i]] = 1 }
            copying = 0; found = 0;
        }
        copying == 0 {
            # A definition starts at column zero and names the class.
            # Two shapes appear: the return type on the same line, and
            # the return type on the line above with "hypervisor::" at
            # column zero. The second needs the line above kept.
            line = $0;
            wants_previous = match(line, /^hypervisor::[a-z_]+\(/);
            if (wants_previous ||
                match(line, /^[A-Za-z_].*hypervisor::[a-z_]+\(/)) {
                name = line;
                sub(/^.*hypervisor::/, "", name);
                sub(/\(.*$/, "", name);
                if (name in want) {
                    copying = 1; found++; seen[name] = 1;
                    if (wants_previous) { print previous }
                    print; next;
                }
            }
            previous = $0;
            next;
        }
        { print }
        /^}$/ { copying = 0 }
        END {
            for (n in want) {
                if (!(n in seen)) {
                    printf("#error \"not found in hypervisor.cpp: %s\"\n", n);
                }
            }
            printf("// extracted %d definitions\n", found);
        }
    ' "$SRC/src/hypervisor/hypervisor.cpp"
    echo '}'
} > real.cpp

EXTRACTED=$(grep -c '^// extracted' real.cpp || true)
if [ "$EXTRACTED" != "1" ]; then
    echo "extraction failed" >&2
    exit 1
fi
grep -q '#error' real.cpp && { grep '#error' real.cpp >&2; exit 1; }
COUNT=$(sed -n 's/^\/\/ extracted \([0-9]*\) .*/\1/p' real.cpp)
if [ "$COUNT" != "4" ]; then
    echo "expected 4 definitions, extracted $COUNT" >&2
    exit 1
fi
echo "$COUNT definitions extracted"

clang++ -std=c++2c -g -O1 -Wall -Wextra -fno-exceptions -fno-rtti \
    -I shim -I ../nested_vmx/shim -I "$SRC/include" -I . \
    harness.cpp real.cpp -o apstart
exec ./apstart
