// GENERATED by build.sh - do not edit, do not commit.
// The bodies below are cut verbatim out of
// hypervisor/src/hypervisor/hypervisor.cpp.
#include "zpp/hypervisor/hypervisor.h"
namespace zpp::hypervisor {
void hypervisor::send_start_up_ipi(std::uint64_t apic,
                                   std::uint64_t vector)
{
    // Delivery mode 110b is start-up, and its vector is the entry point's
    // page number rather than an interrupt vector.
    constexpr std::uint64_t delivery_mode_start_up = 0x6ull << 8;
    constexpr std::uint64_t level_assert = 1ull << 14;

    if (x2apic_enabled()) {
        constexpr std::uint64_t destination_shift = 32;

        arch::x86_64::wrmsr(arch::x86_64::msr::ia32_x2apic_icr,
                            vector | delivery_mode_start_up |
                                (apic << destination_shift));
        return;
    }

    // xAPIC, so the command goes through the APIC page, which the host
    // page table already maps because the interrupt command watch needs
    // it. The destination half is written first: writing the low half is
    // what sends the interrupt, so a destination written after it would
    // be written after the thing that used it.
    constexpr std::uint64_t base_mask = 0xffffff000ull;
    auto base =
        arch::x86_64::rdmsr(arch::x86_64::msr::ia32_apic_base) & base_mask;

    constexpr std::uint64_t interrupt_command_low = 0x300;
    constexpr std::uint64_t interrupt_command_high = 0x310;

    auto * bytes = reinterpret_cast<volatile std::uint8_t *>(base);

    // Eight bits of destination, in 31:24. The x2APIC form above carries
    // thirty-two, which is the other reason these cannot share a line.
    arch::x86_64::write32(bytes + interrupt_command_high,
                          static_cast<std::uint32_t>(apic << 24));
    arch::x86_64::write32(
        bytes + interrupt_command_low,
        static_cast<std::uint32_t>(vector | delivery_mode_start_up |
                                   level_assert));
}
void hypervisor::emulate_init_signal(arch::x86_64::context & context)
{
    auto & vmcs = this->vmcs;

    // This handler must do as little as possible, and that is not a style
    // preference - it is the difference between working and not.
    //
    // A start-up IPI arriving while this processor is not yet in the
    // wait-for-SIPI activity state is discarded rather than queued (SDM
    // 28.2). Under nested virtualization the layer below discards it for
    // the whole time this VMM is in VMX root mode, deliberately - KVM's
    // vmx_apic_init_signal_blocked() is `nested.vmxon && !is_guest_mode`,
    // and the maintainers' position is that it is software's job not to be
    // in root mode when a SIPI arrives. So every instruction between the
    // INIT exit and the resume is a chance to lose the IPI that was
    // supposed to start this processor, and each VMCS write can itself be
    // an exit to the layer below.
    //
    // Windows allows about 210 microseconds between the INIT and the first
    // start-up IPI; the second follows 200 microseconds later. That is the
    // entire budget. So the architectural reset that used to be here now
    // lives in emulate_start_up_ipi, which may take as long as it likes -
    // by the time it runs, the IPI has already been received. The rule to
    // keep is blunt: do not add code to this function.
    //
    // The one read added to that budget on purpose, because the whole
    // adoption design rests on an assumption about it that nothing else
    // records: the activity state this processor was in when the INIT
    // arrived. Everything below sets that field, and record_exit samples
    // it after the fact, so without this the state we *found* is the one
    // thing about an INIT that is unrecoverable afterwards. It answers
    // whether the guest INITed a processor that was running, halted, or
    // already parked waiting for a start-up IPI - and a hang whose cause
    // is the last of those looks like nothing else in the log.
    auto activity_state_found = vmcs.guest_activity_state();

    // What remains is the activity state and the two things that state
    // requires to be clear. Wait-for-SIPI does not permit a pending event:
    // real hardware fails VM entry on a valid VM-entry interruption
    // information field combined with this activity state, even though the
    // nested implementations do not check it.
    vmcs.vm_entry_interruption_information_field(0);
    vmcs.vm_entry_exception_error_code(0);
    vmcs.guest_interruptibility_state(0);

    // There are two ways the start-up IPI that follows this INIT can
    // arrive, and the rest of this function is about choosing one of them
    // and saying so.
    //
    // The architectural way is the wait-for-SIPI activity state: park the
    // processor across a VM entry and let the hardware deliver the IPI as
    // a VM exit. SDM 28.2 is what makes that work and also what makes it
    // fragile - "If a logical processor is not in the wait-for-SIPI
    // activity state when a SIPI arrives, no VM exit occurs and the SIPI
    // is discarded" - so it requires trusting whatever is below this VMM
    // to deliver it. Under nested virtualization that trust is misplaced
    // by design: the IPI is discarded for as long as this VMM is in root
    // mode. So the other way is for the sender to hand the vector over
    // through memory, from its intercepted write to the interrupt command
    // register, and for this processor to wait for it here in root mode
    // where nothing can be lost.
    //
    // The choice is published in start_up_handoff before either wait
    // begins, because the sender reads it to decide whether it may
    // swallow the guest's write. Both sides guessing independently is how
    // a start-up IPI was lost: this processor would park in wait-for-SIPI
    // while the sender, seeing only that the processor was virtualized,
    // handed the vector to a mailbox nobody was reading any more and
    // swallowed the write that would have woken it.
    //
    // Bounded, because a processor spinning forever on an INIT whose
    // start-up IPI never comes is worse than one that gives up: it would
    // take the machine down with no diagnosis. On timeout fall back to the
    // architectural path, which is correct on real hardware and no worse
    // than what came before anywhere else.
    auto cpu = vmcs.vpid() - 1;
    if (cpu >= max_cpus) {
        return;
    }

    this->started_by_start_up_ipi[cpu] = false;

    // Only worth waiting for if the interrupt command register is an MSR,
    // which it is only in x2APIC mode. In xAPIC mode it is a location on
    // the APIC page and the MSR bitmap never sees it, so waiting would
    // burn the whole timeout before falling back for nothing.
    auto x2apic = x2apic_enabled();

    // And only worth waiting for when the hardware path cannot be
    // trusted, which is precisely when something is virtualizing *us*.
    //
    // The architectural wait-for-SIPI path below is correct, cheaper and
    // better tested: it is what real hardware implements and what the
    // Bochs CI exercises on four processors. It fails in exactly one
    // situation - a layer below that discards the start-up IPI while this
    // VMM is in VMX root mode - so the software path is taken in exactly
    // that situation and nowhere else. Bare metal and Bochs never spin.
    //
    // The test is our own CPUID rather than the guest's: this executes in
    // root mode, so it reports what is underneath this VMM. On bare metal
    // the bit is clear. Note the exit handler clears this same bit out of
    // the guest's view of leaf 1, so the two must not be confused - the
    // guest is told there is no hypervisor under it, while we ask whether
    // there is one under us.
    //
    // SDM Vol. 2A, CPUID, "CPUID.01H:ECX Feature Information": bit 31 is
    // reserved and always returns 0 on real hardware, which is why it is
    // the conventional way for a hypervisor to announce itself.
    constexpr std::uint32_t hypervisor_present_bit = (1u << 31);
    std::uint32_t identification[4]{};
    arch::x86_64::cpuid(1, 0, identification);
    auto nested = 0 != (identification[2] & hypervisor_present_bit);

    auto & handoff = this->start_up_handoff[cpu];

    // Whether the software wait was taken at all, which is the one thing
    // worth saying about this on the way out: it is what a sender's
    // decision has to have agreed with.
    auto waited = x2apic && nested;

    // Both facts about this processor are published *before* the wait
    // below, and that ordering is the whole of this fix.
    //
    // The sender does not look at the mailbox first. `start_up_processor`
    // gates on the activity state and only then compare-exchanges into
    // `start_up_handoff`, so a target whose activity record still says
    // "active" has its start-up IPI dropped - and returned as `adopted`,
    // which swallows the guest's write to the interrupt command register.
    // The vector is destroyed rather than delivered.
    //
    // That record is `resume_activity_state`, written by the exit path at
    // the *end* of the handler (see the tail of the exit handler, where it
    // is sampled off vmcs01). So for the entire length of the software
    // wait - up to two million iterations - it holds the value from the
    // exit before the INIT, which is `active`. The window is not a race of
    // instructions: it is the whole wait, and it covers both of the two
    // start-up IPIs SDM 11.4.4.1 step 15 has a guest send.
    //
    // `enter_or_park_l2` already had this right: it writes
    // `l2_activity_state[cpu]` before calling `wait_for_l2_start_up_ipi`,
    // which is why the second-level hand-off works and this one did not.
    // The asymmetry was the bug.
    //
    // Written to the VMCS as well as to the record, and it costs nothing
    // to do it here rather than after: the field is consumed at VM entry,
    // which is far away, and `apply_start_up` puts it back to `active` on
    // every path that delivers a vector.
    vmcs.guest_activity_state(
        arch::x86_64::vmx::activity_state::wait_for_start_up_ipi);
    this->resume_activity_state[cpu] =
        arch::x86_64::vmx::activity_state::wait_for_start_up_ipi;

    if (waited) {
        // Published before the first attempt, so a sender that arrives
        // during the wait finds this processor listening.
        handoff.store(start_up_handoff_state::software_wait);

        // Bounded so a processor cannot spin forever on an INIT whose
        // start-up IPI never arrives. The senders in practice follow
        // within tens of microseconds to ten milliseconds, so this is
        // generous.
        constexpr std::uint32_t start_up_wait_attempts = 2000000;
        for (std::uint32_t attempt{}; attempt < start_up_wait_attempts;
             ++attempt) {
            if (auto state = handoff.load();
                start_up_handoff_state::is_delivered(state)) {
                apply_start_up(context,
                               start_up_handoff_state::vector(state),
                               "init wait");
                return;
            }
            zpp::spin_hint();
        }

        // Giving up, which is the moment the two sides could disagree.
        // A compare-exchange rather than a store because a sender may be
        // handing a vector over at exactly this instant: either this wins
        // and the sender then sees a processor that is no longer
        // listening and issues the IPI to hardware, or the sender wins
        // and the vector is applied here instead. Exactly one of the two
        // happens, which is the whole point - a plain store here would
        // discard a vector that had already been swallowed on the
        // sender's side, and nothing would ever start this processor.
        //
        // The state the exchange found is checked rather than assumed to
        // carry a vector. Nothing else writes it while this processor is
        // listening, so anything else is impossible - and starting a
        // processor at a vector computed from an impossible value would
        // send it to an address nobody chose, which is a worse way to
        // fail than falling through to the architectural wait.
        auto expected = start_up_handoff_state::software_wait;
        if (!handoff.compare_exchange_strong(
                expected, start_up_handoff_state::hardware_wait) &&
            start_up_handoff_state::is_delivered(expected)) {
            apply_start_up(context,
                           start_up_handoff_state::vector(expected),
                           "init race");
            return;
        }
    } else {
        // Waiting on hardware from the start, which is the case on bare
        // metal and under Bochs. Said out loud here rather than left
        // implied, because a sender that assumed otherwise is what used
        // to swallow the IPI this processor is now waiting for.
        handoff.store(start_up_handoff_state::hardware_wait);
    }

    // One log line, and the placement is deliberate: the activity state is
    // written first, so nothing about the diagnostic delays the write the
    // resume depends on. A processor that is never started again is left
    // with this as its last word, next to a recorded exit of INIT with
    // activity state 3 - and the sender's own line, in
    // on_interrupt_command, says which mechanism it then used. The two
    // together are what identifies a swallowed start-up IPI without
    // repeating the investigation: this line says which hand-off this
    // processor is waiting on, that one says which the sender used, and
    // they have to agree.
    log("cpu {} init: found activity {}, waiting for the hardware "
        "start-up ipi, software wait {}",
        vmcs.vpid(),
        activity_state_found,
        waited);
}
std::uint64_t hypervisor::local_apic_id()
{
    // Read out of CPUID rather than out of the local APIC, and that is the
    // whole point of this function.
    //
    // The APIC's own identifier register is only an MSR in x2APIC mode,
    // and this VMM launches before any of that is settled: the firmware is
    // in xAPIC mode, so reading the MSR raises #GP. CPUID answers in every
    // mode and needs no APIC state at all.
    //
    // Not because an INIT returns the APIC to xAPIC mode - it does not,
    // and a comment here used to say so. SDM 13.12.5: "An INIT in this
    // state keeps the x2APIC in the x2APIC mode. The state of the local
    // APIC ID register is preserved (all 32 bits)." Only a reset does
    // that. The consequence to keep is that emulating an INIT must leave
    // IA32_APIC_BASE alone, which apply_start_up does - hardware preserves
    // it and nothing here should be "fixed" to clear it.
    //
    // Getting this wrong was silent. The identifier used to be recorded
    // only when x2APIC happened to be enabled, which on this firmware is
    // never, so the whole table stayed zero and a start-up IPI's
    // destination matched the boot processor's slot by accident.
    constexpr std::uint32_t extended_topology_leaf = 0x1f;
    constexpr std::uint32_t topology_leaf = 0x0b;

    std::uint32_t registers[4]{};

    // The highest leaf this processor answers, so an unsupported one is
    // not asked for - CPUID returns whatever the highest leaf holds
    // instead of failing, which would silently be somebody else's data.
    arch::x86_64::cpuid(0, 0, registers);
    auto highest_leaf = registers[0];

    // SDM Vol. 2A, CPUID: leaf 1FH EDX and leaf 0BH EDX both give "x2APIC
    // ID the current logical processor". The full thirty-two bits, which
    // is what an x2APIC interrupt command register carries as its
    // destination. Leaf 1FH is the newer of the two and is reported as
    // unsupported by a zero in EBX.
    if (highest_leaf >= extended_topology_leaf) {
        arch::x86_64::cpuid(extended_topology_leaf, 0, registers);
        if (registers[1]) {
            return registers[3];
        }
    }

    if (highest_leaf >= topology_leaf) {
        arch::x86_64::cpuid(topology_leaf, 0, registers);
        if (registers[1]) {
            return registers[3];
        }
    }

    // Neither topology leaf, so the initial APIC id out of leaf 1. Eight
    // bits, which is all a processor without x2APIC has.
    constexpr std::uint32_t initial_apic_id_shift = 24;
    arch::x86_64::cpuid(1, 0, registers);
    return registers[1] >> initial_apic_id_shift;
}
std::optional<std::size_t>
hypervisor::processor_slot(std::uint64_t apic_id)
{
    // Under the same lock that guards a launch, because this is the other
    // half of the same resource: it hands out the index every per
    // processor array is addressed by, including the VMXON and VMCS
    // regions and the VPID.
    //
    // Unsynchronised it is a scan followed by an append, and every
    // processor reaches it from its own exit handler - `on_interrupt
    // _command` calls it for any start-up IPI with a physical
    // destination. Two processors asking about two *different* unknown
    // identifiers both read the same `number_of_known_processors`, both
    // take that slot, and the second overwrites the first's `apic_id`
    // entry. The result is two physical processors sharing one slot, and
    // a slot is not a label: `setup_vmcs` writes `vpid(cpu + 1)`, and
    // `initialize_vmx`'s own comment says why that is fatal - "a VMCS may
    // not be active on more than one logical processor".
    //
    // It cannot happen with one application processor, because there is
    // one identifier to allocate and the scan finds it. It becomes
    // possible with two, which is where the processor-count bisect in
    // BACKLOG.md puts the boundary.
    //
    // `start_up_lock` rather than a lock of its own, so that nothing new
    // has to be forced open after an S3 resume - see
    // `resume_from_sleep_on_this_processor`. No caller holds it already:
    // `on_interrupt_command`, `start_up_broadcast` and
    // `start_up_processor` each call this before `start_application
    // _processor` takes it, never inside. It is not recursive, so that
    // has to stay true.
    this->start_up_lock.lock();
    scope_exit unlock{[&] { this->start_up_lock.unlock(); }};

    for (std::size_t slot{}; slot < this->number_of_known_processors;
         ++slot) {
        if (this->apic_id[slot] == apic_id) {
            return slot;
        }
    }

    if (this->number_of_known_processors >= max_cpus) {
        return {};
    }

    auto slot = this->number_of_known_processors++;
    this->apic_id[slot] = apic_id;
    return slot;
}
std::optional<std::uint64_t>
hypervisor::on_interrupt_command(std::uint64_t command)
{
    // The interrupt command register, x2APIC form: vector in the low
    // eight bits, delivery mode in bits 10:8, and the destination APIC id
    // in the upper half rather than in a second register.
    constexpr std::uint64_t vector_mask = 0xff;
    constexpr std::uint64_t delivery_mode_shift = 8;
    constexpr std::uint64_t delivery_mode_mask = 0x7;
    constexpr std::uint64_t delivery_mode_start_up = 6;
    constexpr std::uint64_t destination_shift = 32;

    // The destination shorthand, in bits 19:18. Zero means the destination
    // field names the target; anything else is a broadcast and the
    // destination field means nothing at all.
    constexpr std::uint64_t shorthand_shift = 18;
    constexpr std::uint64_t shorthand_mask = 0x3;
    constexpr std::uint64_t shorthand_none = 0;

    // The destination mode, bit 11. SDM 13.6.1, Figure 13-12 and the table
    // beside it: "Destination Mode - Selects either physical (0) or
    // logical (1) destination mode". A physical destination field is an
    // APIC id; a logical one is an eight-bit message destination address,
    // which SDM 13.6.2.2 says a receiving APIC compares against its own
    // LDR and DFR. It is a bitmask under either model - flat or cluster -
    // and not an identifier at all.
    constexpr std::uint64_t destination_logical = 1ull << 11;

    // INIT, which is logged and otherwise left alone. Logged because it is
    // the first half of the only sequence that starts a processor, and
    // because a hang in that sequence is otherwise invisible: the log then
    // shows what the guest sent, to which destination, and in what order,
    // next to what each target did about it. Cheap - a guest sends INIT
    // only to start or reset a processor, never on a hot path, unlike
    // every other delivery mode reaching this function.
    //
    // Their absence says something too, and it is the first thing to check
    // when a processor never starts: only the x2APIC interrupt command
    // register is an MSR, so a guest still in xAPIC mode writes its
    // command to the APIC page and reaches none of this. No line here at
    // all means the sequence was never seen, not that it was never sent.
    constexpr std::uint64_t delivery_mode_init = 5;

    auto delivery_mode =
        (command >> delivery_mode_shift) & delivery_mode_mask;
    this->ipi_last_command = command;

    // Every command, not only the two that start a processor.
    //
    // A guest hypervisor that has stopped making progress and pokes the
    // interrupt command register every few seconds is sending *something*,
    // and which delivery mode and destination it is decides whether the
    // answer is here or above. Measured on the rig: two writes to
    // 0xfee00000 followed by about 2500 VMX-preemption timer exits at one
    // unchanging RIP, repeating for as long as the guest was left up, with
    // nothing in this log to say what was being sent.
    //
    // Affordable only because the log collapses a repeat into a [times=N]
    // on the line already there - a guest sending the same IPI in a loop
    // costs one line, not one per send. Without that this would be the
    // hottest logger in the tree.
    log("guest ipi command {}, delivery mode {}", command, delivery_mode);

    if (delivery_mode_init == delivery_mode) {
        this->ipi_init_seen = this->ipi_init_seen + 1;
        log("guest init ipi, command {}", command);

        // Forwarded and nothing more, deliberately.
        //
        // This used to also flag every target so the target could apply
        // the INIT to itself at its next exit, on the argument that KVM's
        // `vmx_apic_init_signal_blocked` - `nested.vmxon &&
        // !is_guest_mode` - blocks an INIT for every instant a processor
        // is inside this VMM's code, and that `kvm_apic_accept_events`
        // then *clears* the start-up IPI rather than deferring it.
        //
        // That reasoning is still right and the mechanism was still
        // wrong, because a flag carries no ordering against the start-up
        // IPI that follows. Measured on the rig, from the log ring of a
        // boot that ended in `guest vmxoff`:
        //
        //     guest start-up ipi for cpu 1, vector 2, to hardware
        //     sipi cpu 2 entry_intr 0 idt_vectoring 0
        //     cpu 2 start-up ipi exit, vector 2
        //     cpu 1 applying a guest init the layer below did not deliver
        //     guest start-up ipi for cpu 1, vector 2, to hardware
        //
        // The flagged INIT landed *after* the processor had accepted its
        // start-up IPI and put it back in wait-for-SIPI, so the guest saw
        // no processor start, sent the pair again, and looped until the
        // guest hypervisor gave up and executed vmxoff.
        //
        // A second measured fault in it: the flag was set for INIT level
        // de-assert too - command 0x100008500, level clear and trigger
        // mode level - which architecturally starts nothing at all. So it
        // could invent an INIT, which the comment here used to deny.
        //
        // Restoring this needs a queue with the start-up IPI in it, in
        // the order the guest wrote them, which is what KVM's
        // `apic->pending_events` is. A flag is not that.
        return command;
    }

    if (delivery_mode_start_up != delivery_mode) {
        // Everything else goes out as the guest wrote it. That includes
        // the INIT handled above, and it especially includes INIT: it is
        // what leaves the target waiting for a start-up IPI, which is the
        // state the rest of this needs it in. There is nothing here that
        // improves on any of them.
        return command;
    }

    // Decoded rather than ignored, which is what used to happen. Reading
    // bits 63:32 of a shorthand command yields whatever the guest left
    // there - zero, in practice - and matching that against the table of
    // known processors credited the boot processor with a start-up IPI
    // nobody had sent it.
    this->ipi_start_up_seen = this->ipi_start_up_seen + 1;

    // A broadcast names no destination, so there is nothing to look up.
    // It is resolved against the platform's roster instead and every
    // target run through the same path a targeted command takes.
    //
    // It used to be passed through, on the stated grounds that this VMM
    // could not enumerate what it would be broadcasting to. That was
    // true and the conclusion was still wrong: **this is how Windows
    // starts its processors**, so the case being punted on was the only
    // one that ever happens. Measured on the rig - one broadcast INIT
    // and two broadcast start-up IPIs, shorthand 3, all refused, and not
    // one processor adopted across an entire boot.
    //
    // Passing it through is worse than refusing when a guest hypervisor
    // is above: the processors do start, outside this VMM, so they
    // belong to neither layer. The guest hypervisor's rendezvous never
    // completes and it resets the machine, which is what it did.
    auto shorthand = (command >> shorthand_shift) & shorthand_mask;
    if (shorthand_none != shorthand) {
        auto vector = command & vector_mask;

        if (start_up_broadcast(vector)) {
            return {};
        }

        this->ipi_refused_shorthand = this->ipi_refused_shorthand + 1;
        log("broadcast start-up ipi, shorthand {}, vector {}, no roster "
            "to resolve it against",
            shorthand,
            vector);
        return command;
    }

    // A logical destination is a bitmask, so it is not something
    // processor_slot can be asked about - and asking it anyway is worse
    // than not answering. It compares the value against the table of known
    // APIC ids, fails to match any, and then *allocates a slot for it*,
    // spending an entry on a processor that does not exist and giving the
    // rest of this function a slot index that names the wrong one. With a
    // flat model and a single target the two even coincide often enough to
    // look as though it works: logical id 0x01 is also physical APIC id 1.
    //
    // Passed through rather than adopted, which is the same answer the
    // broadcast case above gets and for the same reason - this VMM has no
    // way to resolve a set of targets into the one processor it would have
    // to start in its own trampoline. That hands those processors to the
    // guest unvirtualized, and is said out loud rather than left to be
    // discovered.
    //
    // Resolving it properly would mean tracking each processor's LDR and
    // DFR and reproducing the match, which is what KVM does:
    // kvm_apic_match_dest in arch/x86/kvm/lapic.c branches on the
    // destination mode before comparing anything, and
    // kvm_apic_match_logical_addr then compares the address against LDR
    // under whichever of flat or cluster DFR selects. Both registers are
    // written through the APIC page or the x2APIC MSRs, so this VMM sees
    // neither today.
    if (0 != (command & destination_logical)) {
        this->ipi_refused_logical = this->ipi_refused_logical + 1;
        log("start-up ipi in logical destination mode, command {}, "
            "not adopted",
            command);
        return command;
    }

    auto destination = command >> destination_shift;
    auto vector = command & vector_mask;

    // Recorded before the attempt, because it is a fact about the guest
    // having asked rather than about the attempt succeeding: a start-up
    // IPI this VMM passes to hardware still means the guest has started
    // that processor, and its duplicate must still be ignored.
    if (auto slot = processor_slot(destination)) {
        this->started_by_guest_start_up_ipi[*slot] = true;
    }

    return (start_up_result::adopted ==
            start_up_processor(destination, vector))
               ? std::optional<std::uint64_t>{}
               : std::optional<std::uint64_t>{command};
}
bool hypervisor::start_up_broadcast(std::uint64_t vector)
{
    // Nothing to resolve against. Answered by the caller passing the
    // guest's own command through, which is what this did before the
    // roster existed - and is still the only thing left when a loader
    // could not supply one.
    if (0 == this->number_of_platform_processors) {
        return false;
    }

    auto self = local_apic_id();

    // "All excluding self", the only broadcast a start-up IPI may use.
    // The other two forms include the sender, which SDM 11.6.1 does not
    // allow for INIT or start-up delivery modes - both references agree,
    // and the guest sends the legal one.
    for (std::size_t i{}; i < this->number_of_platform_processors; ++i) {
        auto destination = this->platform_apic_id[i];
        if (destination == self) {
            continue;
        }

        if (auto slot = processor_slot(destination)) {
            this->started_by_guest_start_up_ipi[*slot] = true;
        }

        if (start_up_result::needs_hardware ==
            start_up_processor(destination, vector)) {
            // The guest's broadcast cannot be forwarded for one target
            // and swallowed for another, so this target gets its own
            // command. Identical in effect to the broadcast the guest
            // wrote, restricted to the processor that still needs it.
            log("broadcast start-up ipi, apic id {} needs hardware, "
                "vector {}",
                destination,
                vector);

            send_start_up_ipi(destination, vector);
        }
    }

    return true;
}
hypervisor::start_up_result hypervisor::start_up_processor(
    std::uint64_t destination, std::uint64_t vector)
{
    auto slot = processor_slot(destination);
    if (!slot) {
        log("no room to track the processor with apic id {}", destination);
        return start_up_result::needs_hardware;
    }

    if (this->processor_virtualized[*slot]) {
        // Already started since its last INIT. A guest sends two start-up
        // IPIs and the second must not be acted on: sending a processor
        // that is already running back to its entry point wedges it in a
        // way indistinguishable from never having started. Swallowed
        // rather than passed on, which is also what the hardware would do
        // with it - SDM 29.7.2: "The active state blocks start-up IPIs
        // (SIPIs). SIPIs that arrive while a logical processor is in the
        // active state and in VMX non-root operation are discarded and do
        // not cause VM exits."
        // Only the *second* start-up IPI of one sequence is ignored, and
        // "one sequence" means since this processor's last INIT from the
        // sender that is asking now.
        //
        // `started_by_start_up_ipi` alone is not that. apply_start_up
        // sets it for every processor it applies a vector to, including
        // the seven the firmware started with its broadcast SIPI long
        // before the guest's operating system existed. So by the time
        // Windows starts its own processors, all seven look "already
        // started" and every one of their start-up IPIs is swallowed.
        //
        // Measured, and this is the whole of the remaining stall: slot 1
        // reports `by_sipi 0` while the log says "already started,
        // ignored" for it - both true, in that order, because the SIPI
        // was swallowed and the INIT that followed then cleared the flag.
        // Hyper-V does not re-send after that, so the processor never
        // receives the vector, never checks in, and gets INITed again.
        //
        // The INIT is what separates them. A processor that has taken one
        // since it was last started is *waiting* for a start-up IPI - SDM
        // 11.4.2 - and the next one is the first of its sequence, not the
        // second. `started_by_start_up_ipi` is cleared by
        // emulate_init_signal, so what is wanted is exactly the flag
        // itself; what was missing is that the firmware's own start-up
        // must not count as the guest's.
        // None of the above survives contact with a guest hypervisor,
        // and the reason is that both flags are a *proxy* for a fact the
        // processor already records.
        //
        // KVM makes exactly one test, in `kvm_apic_accept_events`
        // (lapic.c): "INITs are blocked while CPU is in specific states
        // ..., while SIPIs are dropped if the CPU isn't in wait-for-SIPI
        // (WFS)" - it delivers the vector when the target's mp_state is
        // KVM_MP_STATE_INIT_RECEIVED and drops it otherwise. There is no
        // "already started" flag anywhere in it, and its delivery path
        // (APIC_DM_STARTUP) records every SIPI unconditionally.
        //
        // Measured on the rig with Hyper-V running, which is what the
        // proxy cost: slots 2-7 had *both* flags set while their VMCS
        // activity state was 3 - wait-for-SIPI - so every start-up IPI
        // Hyper-V sent them was swallowed, and its boot processor sat
        // spinning at one RIP taking preemption-timer exits, waiting for
        // processors that were waiting for it. Slot 1 was the control:
        // flags 0 and 1, so this guard never even looked at it, and it
        // was parked in the same state at RIP 0x90e7. Two flags, one of
        // them cleared by INIT, could not describe it; the activity
        // state describes it exactly.
        //
        // So the architectural fact decides. It is written on every
        // resume from the VMCS itself, and SDM 11.4.2 says a processor
        // in wait-for-SIPI is waiting for precisely this message.
        constexpr std::uint64_t wait_for_sipi = 3;

        // Two records to ask, because there are two levels a virtual
        // processor can be waiting at and only one of them is in a VMCS
        // this VMM enters.
        //
        // `resume_activity_state` is the first-level guest's, read off
        // vmcs01 on the way out of the exit handler. `l2_activity_state`
        // is a second-level guest's, and it exists precisely because
        // wait-for-SIPI is never handed to hardware - see
        // `enter_or_park_l2`, which holds the processor in root operation
        // and is listening on the hand-off below at exactly this moment.
        // Asking only the first would drop every start-up IPI a guest
        // hypervisor's own guest sends, since the processor running it
        // reports its hypervisor's activity state, which is active.
        auto activity = (wait_for_sipi == this->l2_activity_state[*slot])
                            ? wait_for_sipi
                            : this->resume_activity_state[*slot];

        if (wait_for_sipi != activity) {
            log("guest start-up ipi for cpu {}, activity {} is not "
                "wait-for-sipi, dropped",
                *slot,
                activity);
            return start_up_result::adopted;
        }

        // Under the hypervisor and out of an INIT, so the target chose
        // which hand-off it is waiting on and published it. Follow that
        // choice rather than assuming one.
        //
        // A compare-exchange, not a store, and that is the whole fix: the
        // target leaves the software wait on its own timeout, and a store
        // would put the vector into a mailbox nobody reads again while
        // swallowing the write that would have woken it. Then nothing
        // starts that processor and the guest waits for it forever. Bare
        // metal never takes the software wait at all, so before this the
        // swallow was unconditional and the loss certain the moment a
        // guest re-started a processor this VMM had already adopted.
        auto expected = start_up_handoff_state::software_wait;
        if (this->start_up_handoff[*slot].compare_exchange_strong(
                expected, start_up_handoff_state::deliver(vector))) {
            log("guest start-up ipi for cpu {}, vector {}, handed over",
                *slot,
                vector);
            return start_up_result::adopted;
        }

        // Not listening, so the hardware path is the only one that can
        // start it and the guest's own write has to go out. This keeps the
        // processor virtualized rather than handing it over: it is in VMX
        // non-root operation parked in the wait-for-SIPI activity state,
        // so SDM 28.2 turns the delivery into a VM exit on it rather than
        // letting it execute the guest's real-mode entry point directly.
        //
        // Correct on bare metal, with one window left that is the
        // architecture's rather than ours: between the target publishing
        // hardware_wait and its VM entry actually reaching that activity
        // state it is still in root mode, and an IPI arriving in that
        // instant is discarded. That window is what the second start-up
        // IPI of the conventional sequence covers - SDM Table 11-1 sends
        // two, 200 microseconds apart, and Vol. 3A's description of
        // delivery mode 110 says outright that a SIPI is not retried by
        // hardware and that reissuing it is software's job.
        //
        // Not futile under a layer either, which is the other half of why
        // this is the right thing to issue. KVM drops a pending start-up
        // IPI only while this VMM is in root mode - lapic.c's
        // kvm_apic_accept_events() clears KVM_APIC_SIPI when
        // kvm_apic_init_sipi_allowed() is false - and that is precisely
        // the window the software hand-off above covers. Once this VMM has
        // entered with an activity state of wait-for-SIPI, KVM's
        // nested_vmx_enter_non_root_mode() records
        // KVM_MP_STATE_INIT_RECEIVED for it, and vmx_check_nested_events()
        // then delivers the IPI as an EXIT_REASON_SIPI_SIGNAL exit. So the
        // two states this VMM publishes line up exactly with the two
        // KVM distinguishes, and each is issued the mechanism that works.
        //
        // The pair of log lines says which was used rather than leaving it
        // to be deduced.
        log("guest start-up ipi for cpu {}, vector {}, to hardware, "
            "target hand-off {}",
            *slot,
            vector,
            expected);
        return start_up_result::needs_hardware;
    }

    // Never seen before, so this is the guest starting it for the first
    // time. Nothing has virtualized it and nothing can, from here - a
    // processor cannot be put into VMX operation by another one. So it is
    // started in this VMM's own trampoline instead, which brings it up
    // under the hypervisor and only then lets it run from the vector the
    // guest asked for.
    if (!this->start_up_memory) {
        log("no start-up memory, cpu {} will run unvirtualized", *slot);
        return start_up_result::needs_hardware;
    }

    if (start_application_processor(*slot, vector)) {
        return start_up_result::adopted;
    }

    // It did not come up. Letting a real start-up IPI reach it is the
    // least bad thing left: the processor is still waiting for one, so
    // the guest gets a processor it can use, unvirtualized. Losing it
    // outright would usually take the guest down with it.
    return start_up_result::needs_hardware;
}
bool hypervisor::start_application_processor(std::size_t slot,
                                             std::uint64_t guest_vector)
{
    if (!this->start_up_memory || (slot >= max_cpus)) {
        return false;
    }

    // One processor at a time, which is what makes a single trampoline,
    // and the single stack below, enough. It also serializes the shared
    // state a launch walks through - the stack index, the virtual
    // processor counter and the VMX region pointers - none of which is
    // correct for two processors at once.
    this->start_up_lock.lock();
    scope_exit unlock{[&] { this->start_up_lock.unlock(); }};

    // Asked again, now that this is exclusive. The test that sent us here
    // is in `start_up_processor` and is made *outside* the lock, so
    // between it and this line another processor can have started this
    // one - two senders answering the same broadcast is enough, and
    // `processor_virtualized[slot]` is written by the target itself from
    // inside its own launch.
    //
    // Going on anyway is not merely wasted work, it is destructive, and
    // the worst of it is one line: `start_up_launched[slot] = false`
    // below. That flag is what `wait_for_ept_acknowledgement` uses to
    // decide which processors must answer an extended page table change -
    // a processor whose flag is clear is skipped, on the argument that it
    // holds no translation. Clearing it for a processor that is running
    // the guest removes it from every rendezvous from then on, silently
    // and permanently, because only `main` ever sets it again. The rest
    // follows: the shared trampoline area is rewritten under a processor
    // that may still be climbing it, and a start-up IPI goes out to one
    // that is executing.
    //
    // Answered as adopted rather than refused, because it is true: the
    // processor is up and virtualized, at the vector the first sender
    // recorded. That is the same answer `start_up_processor` gives a
    // duplicate start-up IPI aimed at a running processor, and SDM 29.7.2
    // says the hardware discards one too - "the active state blocks
    // start-up IPIs (SIPIs)".
    if (this->processor_virtualized[slot]) {
        log("cpu {} was started while this start-up ipi waited for the "
            "lock, vector {} not re-applied",
            slot,
            guest_vector);
        return true;
    }

    this->guest_start_up_vector[slot] = guest_vector;
    this->started_by_trampoline[slot] = true;

    // `start_up_launched[slot] = false` used to be here, and taking it
    // out is the rest of the fix the re-test above only half made.
    //
    // The re-test narrows the window and cannot close it, because the
    // target does not take this lock: it marks itself virtualized and
    // then launched from inside `main`, so a sender can read "not
    // virtualized", have the target mark itself in the gap, and then
    // clear a flag belonging to a processor that is running. Measured in
    // tests/ap_start_up as five rounds in four hundred with the clear
    // still present, and none without it.
    //
    // Nothing needs it cleared. The flag is written true by `main` on the
    // target and false only by `rewind_for_resume`, which runs on one
    // processor with nothing else alive - so a processor that has never
    // launched already reads false, and one that has reads true, which is
    // the answer the wait below wants anyway. Removing the write makes
    // the target the only writer of the "up" edge, which is what a flag
    // that means "this processor is running the guest" has to be.
    //
    // It matters because of who else reads it:
    // `wait_for_ept_acknowledgement` skips a processor whose flag is
    // clear, on the argument that it holds no translation. Clearing it
    // for a running processor takes that processor out of every extended
    // page table rendezvous from then on, silently and for good.

    auto & area = *reinterpret_cast<arch::x86_64::ap_start_up_area *>(
        this->start_up_memory + arch::x86_64::ap_start_up_area_offset);

    // Put the trampoline's own working area back the way the assembler
    // left it, before every start and not just the first.
    //
    // The trampoline relocates three addresses by adding the page's base
    // to them in place, which is correct exactly once. A second processor
    // started from the same blob would add its base to values that already
    // hold one, producing a descriptor table base pointing at nothing -
    // and it faults on the far jump that follows, before it has any
    // interrupt descriptor table, so the machine resets rather than
    // reporting.
    //
    // Measured: with three processors to start, the firmware bootlooped
    // and printed no per-processor result at all, because the check starts
    // every target before polling any of them.
    std::memcpy(
        area.assembly_owned,
        arch::x86_64::zpp_ap_start_up_begin +
            arch::x86_64::ap_start_up_area_offset +
            offsetof(arch::x86_64::ap_start_up_area, assembly_owned),
        sizeof(area.assembly_owned));

    // And the stage, which the memcpy above does not cover: it lives at
    // 0xa2 and assembly_owned ends at 0x80.
    //
    // That made the failure diagnostic lie in the one case it exists for.
    // "Zero means the trampoline never ran a single instruction" is only
    // true until some processor has run it - after that every later
    // failure reports the *previous* processor's stage, and reports it as
    // though it were its own. Read from a real boot as
    // "cpu 2 did not come up, trampoline stage 6" six times over, with
    // the 6 belonging to processor 1, which had succeeded.
    area.stage = static_cast<std::uint8_t>(
        arch::x86_64::ap_start_up_stage::not_started);

    area.argument = slot;
    area.stack_top =
        reinterpret_cast<std::uint64_t>(std::end(this->start_up_stack));

    // The vector is the trampoline page's page number, which is the whole
    // reason that page had to be below one megabyte.
    //
    // Through send_start_up_ipi rather than straight to the x2APIC
    // command MSR, which is what this used to do. That MSR does not exist
    // while the APIC is in xAPIC mode and the write faults - see
    // send_start_up_ipi. A guest that writes its own command to the APIC
    // page is on a processor in exactly that mode, so this path could
    // never have started a processor there.
    send_start_up_ipi(this->apic_id[slot], this->start_up_memory >> 12);

    // Bounded, so that a processor which never arrives costs a delay
    // rather than the machine. Everything it has to do between the IPI and
    // reporting in is a few thousand instructions, so this is generous by
    // orders of magnitude.
    constexpr std::uint32_t launch_wait_attempts = 2000000;
    for (std::uint32_t attempt{}; attempt < launch_wait_attempts;
         ++attempt) {
        if (this->start_up_launched[slot]) {
            log("cpu {} came up on the trampoline after {} attempts, "
                "guest vector {}",
                slot,
                attempt,
                guest_vector);
            return true;
        }
        zpp::spin_hint();
    }

    // The stage is what makes this diagnosable, and it separates the two
    // failures that look identical from here. Zero means the trampoline
    // never ran a single instruction, so the start-up IPI above was never
    // acted on, and the question is then what state the target was in
    // rather than anything about this VMM's own code. That is the whole
    // assumption this path rests on and never checks: SDM 11.4.2 has an
    // application processor "enter a wait-for-SIPI state" on any INIT
    // after the MP protocol has completed, and the sequence in Table 11-1
    // starts one from there. A target somewhere else is not startable this
    // way and nothing here can tell that it is, because an activity state
    // can only be read on the processor holding it.
    //
    // Anything but zero means it did run and died on the climb, at a stage
    // that says where.
    log("cpu {} did not come up after its start-up ipi, apic id {}, "
        "trampoline stage {}",
        slot,
        this->apic_id[slot],
        start_up_trampoline_stage());

    // `started_by_trampoline[slot]` is deliberately **left set**.
    //
    // Clearing it here was the "the trampoline timeout races the processor
    // it is timing out" item in BACKLOG.md, and this is the whole of that
    // race: giving up does not stop the target, it only stops waiting for
    // it. A processor that is merely slow arrives afterwards and reads
    // this flag in `main`, where it decides three things - whether to
    // capture the operating system's registers, whether to build an
    // intermediate GDT by reading the OS descriptor table, and whether to
    // put the OS page table back on the way out. All three are wrong for a
    // processor that came out of the trampoline, and the second one reads
    // through a page table that no longer maps what it names.
    //
    // So the flag describes how this processor arrived, which the timeout
    // does not change. Nothing reads it for a processor that never
    // arrives, and a later attempt sets it again at the top of this
    // function, so leaving it costs nothing and closes the window.
    return false;
}
void hypervisor::apply_start_up(arch::x86_64::context & context,
                                std::uint64_t vector,
                                const char * from,
                                bool first_launch)
{
    auto & vmcs = this->vmcs;

    using segment_descriptor = arch::x86_64::segment_descriptor;

    // A second start-up IPI for a processor already started is ignored.
    // INIT-SIPI-SIPI sends two, and the second would otherwise send a
    // processor that is already running back to its entry point - which
    // wedges it in a way indistinguishable from never having started.
    // Guarded here rather than relying on the hardware to discard the
    // second one, which it does not do reliably.
    if (auto cpu = vmcs.vpid() - 1; cpu < max_cpus) {
        // A processor being launched out of the trampoline is being
        // started for the first time, whatever this flag says. The guard
        // below exists to ignore the *second* start-up IPI of an
        // INIT-SIPI-SIPI sequence, and a launch is not one of those.
        //
        // Honouring it there is a contradiction rather than a
        // conservatism: declining leaves the VMCS holding what
        // setup_vmcs captured, which on this path is this VMM's own C
        // frame - an unusable CS and a RIP inside this module - and VM
        // entry rejects it. Measured as exactly one processor of eight
        // failing per boot, a different one each time, with
        // "cpu N start-up already applied, not applying again, asked by
        // launch" immediately before it.
        if (this->started_by_start_up_ipi[cpu] && !first_launch) {
            // Said out loud, because returning here leaves the guest
            // state as whoever built it last, and on a processor coming
            // out of the trampoline that state is this VMM's own C frame
            // - an unusable CS and a RIP inside this module, which VM
            // entry then rejects. Silently declining to apply start-up
            // state and silently failing to enter look identical from
            // outside, and one of them is this function's fault.
            log("cpu {} start-up already applied, not applying again, "
                "asked by {}",
                cpu,
                from);
            return;
        }
        this->started_by_start_up_ipi[cpu] = true;

        // The hand-off is over, however it arrived. Cleared here because
        // this is the one place both paths end up, and leaving a delivered
        // vector behind would let the next INIT find a start-up nobody
        // sent this time.
        this->start_up_handoff[cpu].store(start_up_handoff_state::none);
    }

    // Everything below is the state an INIT leaves behind, applied here
    // rather than in the INIT handler because here there is time. SDM
    // Table 12-1, "IA-32 and Intel 64 Processor States Following Power-up,
    // Reset, or INIT", INIT column.
    constexpr std::uint64_t rflags_after_init = 0x2;
    constexpr std::uint64_t dr6_after_init = 0xffff0ff0;
    constexpr std::uint64_t dr7_after_init = 0x400;
    constexpr std::uint64_t cr4_after_init = 0;
    constexpr std::uint64_t real_mode_segment_limit = 0xffff;
    constexpr std::uint64_t descriptor_table_limit_after_init = 0xffff;

    // SDM Table 12-1 gives 0x60000010 in the CR0 row's INIT column, but
    // footnote 2 on that row qualifies it: "The CD and NW flags are
    // unchanged, bit 4 is set to 1, all other bits are cleared." The
    // 0x60000010 is the power-up value, where CD and NW happen to be set -
    // taking it literally for an INIT would disable this processor's
    // caches for the rest of its life.
    constexpr std::uint64_t preserved_across_init =
        arch::x86_64::cr0_bits::cache_disable |
        arch::x86_64::cr0_bits::not_write_through;
    auto cr0_after_init = arch::x86_64::cr0_bits::extension_type |
                          (vmcs.guest_cr0() & preserved_across_init);

    // The two bits VMX will not let a guest clear: CR0.NE and CR4.VMXE are
    // required to be set by IA32_VMX_CR0_FIXED0 and IA32_VMX_CR4_FIXED0
    // (SDM A.7 and A.8), and unrestricted guest exempts only PE and PG -
    // so a literally architectural CR0 and CR4 would fail VM entry. The
    // architectural values go into the read shadows, which is where a
    // guest looks once those bits are owned by the host.
    constexpr std::uint64_t cr0_never_clear =
        arch::x86_64::cr0_bits::numeric_error;
    constexpr std::uint64_t cr4_never_clear =
        arch::x86_64::cr4_bits::vmx_enable;

    // A real mode segment: sixteen bit, byte granular, limit 0xffff. The
    // access rights the VMCS wants are the descriptor's, so they are built
    // out of a descriptor rather than written as a number.
    auto real_mode_segment = [](segment_descriptor::segment_type type,
                                bool system) {
        segment_descriptor descriptor;
        descriptor.limit(real_mode_segment_limit);
        descriptor.base(0);
        descriptor.type(type);
        descriptor.system(system);
        descriptor.privilege_level(0);
        descriptor.present(true);
        descriptor.available_for_system_use(false);
        descriptor.code_64_bit(false);
        descriptor.default_operation_size(false);
        descriptor.granularity(false);
        return descriptor.vmx_access_rights();
    };

    auto code_access_rights = real_mode_segment(
        segment_descriptor::segment_type::code_execute_read_accessed,
        false);
    auto data_access_rights = real_mode_segment(
        segment_descriptor::segment_type::data_read_write_accessed, false);
    auto ldtr_access_rights =
        real_mode_segment(segment_descriptor::segment_type::ldt, true);
    auto tr_access_rights = real_mode_segment(
        segment_descriptor::segment_type::tss_busy, true);

    vmcs.guest_cr0(cr0_after_init | cr0_never_clear);
    vmcs.cr0_read_shadow(cr0_after_init);
    vmcs.guest_cr3(0);
    vmcs.guest_cr4(cr4_after_init | cr4_never_clear);
    vmcs.cr4_read_shadow(cr4_after_init);

    // Long mode is gone with CR0.PG, and the entry control has to agree or
    // VM entry fails its consistency checks.
    //
    // The guest IA32_EFER field is deliberately not written. Without the
    // "load IA32_EFER" VM-entry control - which this VMCS does not set -
    // the field is ignored, and VM entry instead loads EFER.LMA from the
    // control cleared below and leaves LME alone when CR0.PG is being
    // loaded as zero, which it is here. Writing the field would look like
    // it cleared EFER when it does nothing at all.
    vmcs.vm_entry_controls(
        vmcs.vm_entry_controls() &
        ~arch::x86_64::vmx::vm_entry_controls::ia_32e_mode_guest);

    vmcs.guest_rflags(rflags_after_init);
    vmcs.guest_rsp(0);
    vmcs.guest_dr7(dr7_after_init);

    // Every data segment is sixteen bit, based at zero, selector zero.
    vmcs.guest_ss_selector(0);
    vmcs.guest_ss_base(0);
    vmcs.guest_ss_limit(real_mode_segment_limit);
    vmcs.guest_ss_access_rights(data_access_rights);

    vmcs.guest_ds_selector(0);
    vmcs.guest_ds_base(0);
    vmcs.guest_ds_limit(real_mode_segment_limit);
    vmcs.guest_ds_access_rights(data_access_rights);

    vmcs.guest_es_selector(0);
    vmcs.guest_es_base(0);
    vmcs.guest_es_limit(real_mode_segment_limit);
    vmcs.guest_es_access_rights(data_access_rights);

    vmcs.guest_fs_selector(0);
    vmcs.guest_fs_base(0);
    vmcs.guest_fs_limit(real_mode_segment_limit);
    vmcs.guest_fs_access_rights(data_access_rights);

    vmcs.guest_gs_selector(0);
    vmcs.guest_gs_base(0);
    vmcs.guest_gs_limit(real_mode_segment_limit);
    vmcs.guest_gs_access_rights(data_access_rights);

    vmcs.guest_ldtr_selector(0);
    vmcs.guest_ldtr_base(0);
    vmcs.guest_ldtr_limit(real_mode_segment_limit);
    vmcs.guest_ldtr_access_rights(ldtr_access_rights);

    vmcs.guest_tr_selector(0);
    vmcs.guest_tr_base(0);
    vmcs.guest_tr_limit(real_mode_segment_limit);
    vmcs.guest_tr_access_rights(tr_access_rights);

    vmcs.guest_gdtr_base(0);
    vmcs.guest_gdtr_limit(descriptor_table_limit_after_init);
    vmcs.guest_idtr_base(0);
    vmcs.guest_idtr_limit(descriptor_table_limit_after_init);

    vmcs.guest_pending_debug_exceptions(0);

    // The general purpose registers are architecturally defined after an
    // INIT too, and they are not in the VMCS - they live in the context
    // this VMM saved on the way in and restores on the way out. Same
    // table: EAX zero, EDX the family, model and stepping, the rest zero.
    std::uint32_t identification[4]{};
    arch::x86_64::cpuid(1, 0, identification);

    context.rax = 0;
    context.rbx = 0;
    context.rcx = 0;
    context.rdx = identification[0];

    // Zeroed for the same reason as the rest, and load bearing on the
    // launch path: vm_launch takes the guest's RIP and RSP from this
    // context rather than from the VMCS, so leaving either holding where
    // this VMM happened to be would start the guest there instead of at
    // its entry point. On the VM exit path both are overwritten again
    // before the resume, so this costs nothing there.
    context.rip = 0;
    context.rsp = 0;
    context.rbp = 0;
    context.rsi = 0;
    context.rdi = 0;
    context.r8 = 0;
    context.r9 = 0;
    context.r10 = 0;
    context.r11 = 0;
    context.r12 = 0;
    context.r13 = 0;
    context.r14 = 0;
    context.r15 = 0;

    // DR6 is not a VMCS guest field - the guest and host share the
    // register - so the architectural value has to be written to the real
    // one while running on this processor.
    arch::x86_64::dr6(dr6_after_init);

    // SDM 12.1: during an INIT "the TLBs and BTB are invalidated as with a
    // hardware reset", and the same paragraph describes INIT as the method
    // for "switching from protected to real-address mode" - exactly the
    // transition just made. With VPID enabled the processor tags its
    // cached translations, so they survive it and must be invalidated by
    // hand. Single-context, so other processors are left alone.
    constexpr std::uint64_t invvpid_single_context = 1;

    struct alignas(0x10) invvpid_descriptor
    {
        std::uint64_t vpid{};
        std::uint64_t linear_address{};
    };

    invvpid_descriptor descriptor{vmcs.vpid(), 0};
    if (arch::x86_64::vmx::invvpid(invvpid_single_context, &descriptor)) {
        log("invvpid failed on cpu {}", vmcs.vpid());
    }

    // And now where the start-up IPI says to begin. Shifts that turn the
    // vector into a segment: the vector is a page number, so the segment
    // is the vector scaled by a page, and the selector is that base
    // shifted down by the four bits real mode already implies. Matches
    // KVM's kvm_vcpu_deliver_sipi_vector(), which sets the same three
    // fields and nothing else.
    constexpr std::uint64_t vector_to_selector_shift = 8;
    constexpr std::uint64_t vector_to_base_shift = 12;

    vmcs.guest_cs_selector(vector << vector_to_selector_shift);
    vmcs.guest_cs_base(vector << vector_to_base_shift);
    vmcs.guest_cs_limit(real_mode_segment_limit);
    vmcs.guest_cs_access_rights(code_access_rights);
    vmcs.guest_rip(0);

    // Runnable again.
    vmcs.guest_activity_state(arch::x86_64::vmx::activity_state::active);
}
std::expected<void, zpp::error>
hypervisor::enter_root_mode(std::size_t cpu)
{
    // This processor's own regions, as locals, and that is a fix rather
    // than a tidy-up.
    //
    // They used to be two members `initialize_vmx` wrote and this
    // function read back. Everything else about a launch is indexed by
    // the slot; these two were a hand-off through shared state, and the
    // window between the write and the VMXON below is not protected by
    // anything on this processor - `start_up_lock` is held by the
    // *starter*, and it is released on its own timeout as well as on
    // success. A second processor entering `initialize_vmx` inside that
    // window overwrote both, and this one then executed VMPTRLD on the
    // other's VMCS. SDM 25.1 and the comment in `initialize_vmx`: a VMCS
    // may not be active on more than one logical processor.
    //
    // Derived here rather than passed in, so there is no way to call this
    // with a slot that disagrees with the regions - the same shape
    // `own_vmxon_region_physical` and `own_vmcs_region_physical` already
    // have for the sleep path. They cannot be reused: both read the slot
    // out of `vmcs.vpid()`, and no VMCS is current yet.
    //
    // Addressable because VMXON, VMCLEAR and VMPTRLD take the address of
    // a physical address rather than the address itself.
    if (cpu >= max_cpus) {
        return std::unexpected(zpp::error{error::too_many_processors});
    }

    auto vmx_physical =
        this->host_page_table.virtual_to_physical(&this->vmx[cpu]);
    auto vmcs_physical =
        this->host_page_table.virtual_to_physical(&this->vmx_vmcs[cpu]);

    // Into the state VMX requires, each behind a guard: every step below
    // can fail, and a failure has to leave the loader the machine it was
    // still running on.
    auto cr0 = arch::x86_64::cr0();
    auto cr4 = arch::x86_64::cr4();

    arch::x86_64::cr0(this->host_cr0);
    scope_exit restore_cr0{[&] { arch::x86_64::cr0(cr0); }};

    arch::x86_64::cr4(this->host_cr4);
    scope_exit restore_cr4{[&] { arch::x86_64::cr4(cr4); }};

    // Let VMXON through in IA32_FEATURE_CONTROL. Without this vmxon raises
    // a general protection fault rather than failing with the carry flag,
    // which is how the missing host IDT used to turn into a triple fault.
    // The MSR is per logical processor, so this belongs here rather than
    // in the once-per-boot setup.
    if (auto result = enable_vmx_in_feature_control(); !result) {
        return result;
    }

    if (arch::x86_64::vmx::vmxon(&vmx_physical)) {
        return std::unexpected(zpp::error{error::vmxon_failed});
    }
    scope_exit turn_off_vmx{arch::x86_64::vmx::vmxoff};

    // VMCLEAR is the only thing that sets the launch state to clear, and
    // VMLAUNCH requires clear (SDM 27.1). The state lives in the region
    // itself and cannot be read back, so it has to be set here.
    if (arch::x86_64::vmx::vmclear(&vmcs_physical)) {
        return std::unexpected(zpp::error{error::vmclear_failed});
    }

    if (arch::x86_64::vmx::vmptrld(&vmcs_physical)) {
        return std::unexpected(zpp::error{error::vmptrld_failed});
    }

    // Released, not run: from here the processor stays in VMX operation
    // with these registers, which is what this function is for. main
    // takes over the undoing.
    turn_off_vmx.release();
    restore_cr4.release();
    restore_cr0.release();
    return {};
}
bool hypervisor::x2apic_enabled()
{
    // IA32_APIC_BASE.EXTD. With it clear the local APIC is in xAPIC mode,
    // its registers live on the APIC page rather than in MSR space, and
    // touching an x2APIC MSR raises #GP. SDM 13.12.1.
    constexpr std::uint64_t apic_base_x2apic_enabled = (1ull << 10);
    return 0 != (arch::x86_64::rdmsr(arch::x86_64::msr::ia32_apic_base) &
                 apic_base_x2apic_enabled);
}
// extracted 11 definitions
}
