include ../environment.config

CLANG_TARGET := $(TARGET_ABI)-pc-win32-msvc

ifeq ($(TARGET_ABI), x86)
	MICROSOFT_DEFINES := -D_MT -D_WIN32 -D_X86_
	VISUAL_STUDIO_PROCESSOR := x86
	WINDOWS_KITS_PROCESSOR := x86
else ifeq ($(TARGET_ABI), x86_64)
	MICROSOFT_DEFINES := -D_MT -D_WIN32 -D_WIN64 -D_AMD64_
	VISUAL_STUDIO_PROCESSOR := x64
	WINDOWS_KITS_PROCESSOR := x64
else ifneq ($(TARGET_ABI),)
$(error Unsupported target)
endif

EMPTY := 
SPACE := $(EMPTY) $(EMPTY)

VISUAL_STUDIO_ROOT := $(subst $(SPACE),+,$(VISUAL_STUDIO_ROOT))
WINDOWS_KITS_ROOT := $(subst $(SPACE),+,$(WINDOWS_KITS_ROOT))

VISUAL_STUDIO_INCLUDES := $(VISUAL_STUDIO_ROOT)/include
VISUAL_STUDIO_LIBRARIES := $(VISUAL_STUDIO_ROOT)/lib/$(VISUAL_STUDIO_PROCESSOR)

WINDOWS_KITS_INCLUDES := \
	$(WINDOWS_KITS_ROOT)/Include/$(WINDOWS_KITS_VERSION)/km \
	$(WINDOWS_KITS_ROOT)/Include/$(WINDOWS_KITS_VERSION)/ucrt \
	$(WINDOWS_KITS_ROOT)/Include/$(WINDOWS_KITS_VERSION)/um \
	$(WINDOWS_KITS_ROOT)/Include/$(WINDOWS_KITS_VERSION)/shared \
	$(WINDOWS_KITS_ROOT)/Include/$(WINDOWS_KITS_VERSION)/winrt

WINDOWS_KITS_LIBRARIES := \
	$(WINDOWS_KITS_ROOT)/Lib/$(WINDOWS_KITS_VERSION)/ucrt/$(WINDOWS_KITS_PROCESSOR) \
	$(WINDOWS_KITS_ROOT)/Lib/$(WINDOWS_KITS_VERSION)/um/$(WINDOWS_KITS_PROCESSOR) \
	$(WINDOWS_KITS_ROOT)/Lib/$(WINDOWS_KITS_VERSION)/km/$(WINDOWS_KITS_PROCESSOR)

ENVIRONMENT_INCLUDES := $(WINDOWS_KITS_INCLUDES) $(VISUAL_STUDIO_INCLUDES)
ENVIRONMENT_LIBRARIES := $(VISUAL_STUDIO_LIBRARIES) $(WINDOWS_KITS_LIBRARIES)

ENVIRONMENT_INCLUDES := $(patsubst %, -isystem %, $(ENVIRONMENT_INCLUDES))
ENVIRONMENT_LIBRARIES := $(patsubst %, -L %, $(ENVIRONMENT_LIBRARIES))

ENVIRONMENT_INCLUDES := $(subst +,$(SPACE),$(ENVIRONMENT_INCLUDES))
ENVIRONMENT_LIBRARIES := $(subst +,$(SPACE),$(ENVIRONMENT_LIBRARIES))

ENVIRONMENT_FLAGS := \
	-target $(CLANG_TARGET) \
	-nostdinc \
	-nostdinc++ \
	-D_CRT_SECURE_NO_WARNINGS \
	-D_CRT_SECURE_NO_DEPRECATE \
	-D_NO_CRT_STDIO_INLINE \
	$(MICROSOFT_DEFINES) \
	-U__GNUC__ \
	-U__gnu_linux__ \
	-U__GNUC_MINOR__ \
	-U__GNUC_PATCHLEVEL__ \
	-U__GNUC_STDC_INLINE__ \
	-fuse-ld=lld \
	-Wl,-ignore:4217

CC := clang \
	$(ENVIRONMENT_INCLUDES) \
	$(ENVIRONMENT_LIBRARIES) \
	$(ENVIRONMENT_FLAGS)

CXX := clang++ \
	$(ENVIRONMENT_INCLUDES) \
	$(ENVIRONMENT_LIBRARIES) \
	$(ENVIRONMENT_FLAGS)

AR := ar
AS := $(CC)
LINK := $(CXX)
STRIP = strip
