#!/bin/sh
# Harness for the interrupt command register's decode path.
#
#   shim/            a stand-in hypervisor.h carrying only what the decode
#                    touches, so the REAL processor_slot,
#                    on_interrupt_command and start_up_broadcast compile
#                    natively.
#   ../nested_vmx/shim
#                    the asm.h, vmx/asm.h and diag/log.h shims, shared
#                    with the other harnesses. This directory comes first
#                    on the include path so its hypervisor.h wins.
#   harness.cpp      the fake roster, the fake hardware and the tests.
#   real.cpp         generated below - the function bodies cut out of
#                    hypervisor.cpp, byte for byte.
#
# Cut by NAME rather than by line number, the same way tests/watched_page
# and tests/ap_start_up do it: the cut then moves with the code, and a
# renamed or deleted function fails the build here instead of silently
# testing nothing. The count is checked below for the same reason.
#
# Never run clang-format over this file. It reflows a shell script as C++
# and destroys it, exactly as CLAUDE.md records for Markdown.
set -e
cd "$(dirname "$0")"
SRC=${SRC:-"$(cd ../.. && pwd)/hypervisor"}

WANTED='processor_slot on_interrupt_command start_up_broadcast note_apic_mode intercept_interrupt_command'

{
    echo '// GENERATED by build.sh - do not edit, do not commit.'
    echo '// The bodies below are cut verbatim out of'
    echo '// hypervisor/src/hypervisor/hypervisor.cpp.'
    echo '#include "zpp/hypervisor/hypervisor.h"'
    echo 'namespace zpp::hypervisor {'
    awk -v wanted="$(echo $WANTED)" '
        BEGIN {
            split(wanted, names, " ");
            for (i in names) { want[names[i]] = 1 }
            copying = 0; found = 0;
        }
        copying == 0 {
            # A definition starts at column zero and names the class.
            # Two shapes appear: the return type on the same line, and
            # the return type on the line above with "hypervisor::" at
            # column zero. The second needs the line above kept.
            line = $0;
            wants_previous = match(line, /^hypervisor::[a-z_]+\(/);
            if (wants_previous ||
                match(line, /^[A-Za-z_].*hypervisor::[a-z_]+\(/)) {
                name = line;
                sub(/^.*hypervisor::/, "", name);
                sub(/\(.*$/, "", name);
                if (name in want) {
                    copying = 1; found++; seen[name] = 1;
                    if (wants_previous) { print previous }
                    print; next;
                }
            }
            previous = $0;
            next;
        }
        { print }
        /^}$/ { copying = 0 }
        END {
            for (n in want) {
                if (!(n in seen)) {
                    printf("#error \"not found in the hypervisor sources: %s\"\n", n);
                }
            }
            printf("// extracted %d definitions\n", found);
        }
    ' "$SRC/src/hypervisor/hypervisor.cpp" \
      "$SRC/src/hypervisor/local_apic.cpp"
    echo '}'
} > real.cpp

EXTRACTED=$(grep -c '^// extracted' real.cpp || true)
if [ "$EXTRACTED" != "1" ]; then
    echo "extraction failed" >&2
    exit 1
fi
grep -q '#error' real.cpp && { grep '#error' real.cpp >&2; exit 1; }
COUNT=$(sed -n 's/^\/\/ extracted \([0-9]*\) .*/\1/p' real.cpp)
if [ "$COUNT" != "5" ]; then
    echo "expected 5 definitions, extracted $COUNT" >&2
    exit 1
fi
echo "$COUNT definitions extracted"

clang++ -std=c++2c -g -O1 -Wall -Wextra -fno-exceptions -fno-rtti \
    -I shim -I ../nested_vmx/shim -I "$SRC/include" -I . \
    harness.cpp real.cpp -o localapic
exec ./localapic
