// GENERATED by build.sh - do not edit, do not commit.
// The bodies below are cut verbatim out of
// hypervisor/src/hypervisor/hypervisor.cpp.
#include "zpp/hypervisor/hypervisor.h"
namespace zpp::hypervisor {
std::optional<std::size_t>
hypervisor::processor_slot(std::uint64_t apic_id)
{
    // Under the same lock that guards a launch, because this is the other
    // half of the same resource: it hands out the index every per
    // processor array is addressed by, including the VMXON and VMCS
    // regions and the VPID.
    //
    // Unsynchronised it is a scan followed by an append, and every
    // processor reaches it from its own exit handler - `on_interrupt
    // _command` calls it for any start-up IPI with a physical
    // destination. Two processors asking about two *different* unknown
    // identifiers both read the same `number_of_known_processors`, both
    // take that slot, and the second overwrites the first's `apic_id`
    // entry. The result is two physical processors sharing one slot, and
    // a slot is not a label: `setup_vmcs` writes `vpid(cpu + 1)`, and
    // `initialize_vmx`'s own comment says why that is fatal - "a VMCS may
    // not be active on more than one logical processor".
    //
    // It cannot happen with one application processor, because there is
    // one identifier to allocate and the scan finds it. It becomes
    // possible with two, which is where the processor-count bisect in
    // BACKLOG.md puts the boundary.
    //
    // `start_up_lock` rather than a lock of its own, so that nothing new
    // has to be forced open after an S3 resume - see
    // `resume_from_sleep_on_this_processor`. No caller holds it already:
    // `on_interrupt_command`, `start_up_broadcast` and
    // `start_up_processor` each call this before `start_application
    // _processor` takes it, never inside. It is not recursive, so that
    // has to stay true.
    this->start_up_lock.lock();
    scope_exit unlock{[&] { this->start_up_lock.unlock(); }};

    for (std::size_t slot{}; slot < this->number_of_known_processors;
         ++slot) {
        if (this->apic_id[slot] == apic_id) {
            return slot;
        }
    }

    if (this->number_of_known_processors >= max_cpus) {
        return {};
    }

    auto slot = this->number_of_known_processors++;
    this->apic_id[slot] = apic_id;
    return slot;
}
std::optional<std::uint64_t>
hypervisor::on_interrupt_command(std::uint64_t command)
{
    // The interrupt command register, x2APIC form: vector in the low
    // eight bits, delivery mode in bits 10:8, and the destination APIC id
    // in the upper half rather than in a second register.
    constexpr std::uint64_t vector_mask = 0xff;
    constexpr std::uint64_t delivery_mode_shift = 8;
    constexpr std::uint64_t delivery_mode_mask = 0x7;
    constexpr std::uint64_t delivery_mode_start_up = 6;
    constexpr std::uint64_t destination_shift = 32;

    // The destination shorthand, in bits 19:18. Zero means the destination
    // field names the target; anything else is a broadcast and the
    // destination field means nothing at all.
    constexpr std::uint64_t shorthand_shift = 18;
    constexpr std::uint64_t shorthand_mask = 0x3;
    constexpr std::uint64_t shorthand_none = 0;

    // The destination mode, bit 11. SDM 13.6.1, Figure 13-12 and the table
    // beside it: "Destination Mode - Selects either physical (0) or
    // logical (1) destination mode". A physical destination field is an
    // APIC id; a logical one is an eight-bit message destination address,
    // which SDM 13.6.2.2 says a receiving APIC compares against its own
    // LDR and DFR. It is a bitmask under either model - flat or cluster -
    // and not an identifier at all.
    constexpr std::uint64_t destination_logical = 1ull << 11;

    // INIT, which is logged and otherwise left alone. Logged because it is
    // the first half of the only sequence that starts a processor, and
    // because a hang in that sequence is otherwise invisible: the log then
    // shows what the guest sent, to which destination, and in what order,
    // next to what each target did about it. Cheap - a guest sends INIT
    // only to start or reset a processor, never on a hot path, unlike
    // every other delivery mode reaching this function.
    //
    // Their absence says something too, and it is the first thing to check
    // when a processor never starts: only the x2APIC interrupt command
    // register is an MSR, so a guest still in xAPIC mode writes its
    // command to the APIC page and reaches none of this. No line here at
    // all means the sequence was never seen, not that it was never sent.
    constexpr std::uint64_t delivery_mode_init = 5;

    auto delivery_mode =
        (command >> delivery_mode_shift) & delivery_mode_mask;
    this->ipi_last_command = command;

    // Every command, not only the two that start a processor.
    //
    // A guest hypervisor that has stopped making progress and pokes the
    // interrupt command register every few seconds is sending *something*,
    // and which delivery mode and destination it is decides whether the
    // answer is here or above. Measured on the rig: two writes to
    // 0xfee00000 followed by about 2500 VMX-preemption timer exits at one
    // unchanging RIP, repeating for as long as the guest was left up, with
    // nothing in this log to say what was being sent.
    //
    // Affordable only because the log collapses a repeat into a [times=N]
    // on the line already there - a guest sending the same IPI in a loop
    // costs one line, not one per send. Without that this would be the
    // hottest logger in the tree.
    log("guest ipi command {}, delivery mode {}", command, delivery_mode);

    if (delivery_mode_init == delivery_mode) {
        this->ipi_init_seen = this->ipi_init_seen + 1;
        log("guest init ipi, command {}", command);

        // Forwarded and nothing more, deliberately.
        //
        // This used to also flag every target so the target could apply
        // the INIT to itself at its next exit, on the argument that KVM's
        // `vmx_apic_init_signal_blocked` - `nested.vmxon &&
        // !is_guest_mode` - blocks an INIT for every instant a processor
        // is inside this VMM's code, and that `kvm_apic_accept_events`
        // then *clears* the start-up IPI rather than deferring it.
        //
        // That reasoning is still right and the mechanism was still
        // wrong, because a flag carries no ordering against the start-up
        // IPI that follows. Measured on the rig, from the log ring of a
        // boot that ended in `guest vmxoff`:
        //
        //     guest start-up ipi for cpu 1, vector 2, to hardware
        //     sipi cpu 2 entry_intr 0 idt_vectoring 0
        //     cpu 2 start-up ipi exit, vector 2
        //     cpu 1 applying a guest init the layer below did not deliver
        //     guest start-up ipi for cpu 1, vector 2, to hardware
        //
        // The flagged INIT landed *after* the processor had accepted its
        // start-up IPI and put it back in wait-for-SIPI, so the guest saw
        // no processor start, sent the pair again, and looped until the
        // guest hypervisor gave up and executed vmxoff.
        //
        // A second measured fault in it: the flag was set for INIT level
        // de-assert too - command 0x100008500, level clear and trigger
        // mode level - which architecturally starts nothing at all. So it
        // could invent an INIT, which the comment here used to deny.
        //
        // Restoring this needs a queue with the start-up IPI in it, in
        // the order the guest wrote them, which is what KVM's
        // `apic->pending_events` is. A flag is not that.
        return command;
    }

    if (delivery_mode_start_up != delivery_mode) {
        // Everything else goes out as the guest wrote it. That includes
        // the INIT handled above, and it especially includes INIT: it is
        // what leaves the target waiting for a start-up IPI, which is the
        // state the rest of this needs it in. There is nothing here that
        // improves on any of them.
        return command;
    }

    // Decoded rather than ignored, which is what used to happen. Reading
    // bits 63:32 of a shorthand command yields whatever the guest left
    // there - zero, in practice - and matching that against the table of
    // known processors credited the boot processor with a start-up IPI
    // nobody had sent it.
    this->ipi_start_up_seen = this->ipi_start_up_seen + 1;

    // A broadcast names no destination, so there is nothing to look up.
    // It is resolved against the platform's roster instead and every
    // target run through the same path a targeted command takes.
    //
    // It used to be passed through, on the stated grounds that this VMM
    // could not enumerate what it would be broadcasting to. That was
    // true and the conclusion was still wrong: **this is how Windows
    // starts its processors**, so the case being punted on was the only
    // one that ever happens. Measured on the rig - one broadcast INIT
    // and two broadcast start-up IPIs, shorthand 3, all refused, and not
    // one processor adopted across an entire boot.
    //
    // Passing it through is worse than refusing when a guest hypervisor
    // is above: the processors do start, outside this VMM, so they
    // belong to neither layer. The guest hypervisor's rendezvous never
    // completes and it resets the machine, which is what it did.
    auto shorthand = (command >> shorthand_shift) & shorthand_mask;
    if (shorthand_none != shorthand) {
        auto vector = command & vector_mask;

        if (start_up_broadcast(vector)) {
            return {};
        }

        this->ipi_refused_shorthand = this->ipi_refused_shorthand + 1;
        log("broadcast start-up ipi, shorthand {}, vector {}, no roster "
            "to resolve it against",
            shorthand,
            vector);
        return command;
    }

    // A logical destination is a bitmask, so it is not something
    // processor_slot can be asked about - and asking it anyway is worse
    // than not answering. It compares the value against the table of known
    // APIC ids, fails to match any, and then *allocates a slot for it*,
    // spending an entry on a processor that does not exist and giving the
    // rest of this function a slot index that names the wrong one. With a
    // flat model and a single target the two even coincide often enough to
    // look as though it works: logical id 0x01 is also physical APIC id 1.
    //
    // Passed through rather than adopted, which is the same answer the
    // broadcast case above gets and for the same reason - this VMM has no
    // way to resolve a set of targets into the one processor it would have
    // to start in its own trampoline. That hands those processors to the
    // guest unvirtualized, and is said out loud rather than left to be
    // discovered.
    //
    // Resolving it properly would mean tracking each processor's LDR and
    // DFR and reproducing the match, which is what KVM does:
    // kvm_apic_match_dest in arch/x86/kvm/lapic.c branches on the
    // destination mode before comparing anything, and
    // kvm_apic_match_logical_addr then compares the address against LDR
    // under whichever of flat or cluster DFR selects. Both registers are
    // written through the APIC page or the x2APIC MSRs, so this VMM sees
    // neither today.
    if (0 != (command & destination_logical)) {
        this->ipi_refused_logical = this->ipi_refused_logical + 1;
        log("start-up ipi in logical destination mode, command {}, "
            "not adopted",
            command);
        return command;
    }

    auto destination = command >> destination_shift;
    auto vector = command & vector_mask;

    // Recorded before the attempt, because it is a fact about the guest
    // having asked rather than about the attempt succeeding: a start-up
    // IPI this VMM passes to hardware still means the guest has started
    // that processor, and its duplicate must still be ignored.
    if (auto slot = processor_slot(destination)) {
        this->started_by_guest_start_up_ipi[*slot] = true;
    }

    return (start_up_result::adopted ==
            start_up_processor(destination, vector))
               ? std::optional<std::uint64_t>{}
               : std::optional<std::uint64_t>{command};
}
bool hypervisor::start_up_broadcast(std::uint64_t vector)
{
    // Nothing to resolve against. Answered by the caller passing the
    // guest's own command through, which is what this did before the
    // roster existed - and is still the only thing left when a loader
    // could not supply one.
    if (0 == this->number_of_platform_processors) {
        return false;
    }

    auto self = local_apic_id();

    // "All excluding self", the only broadcast a start-up IPI may use.
    // The other two forms include the sender, which SDM 11.6.1 does not
    // allow for INIT or start-up delivery modes - both references agree,
    // and the guest sends the legal one.
    for (std::size_t i{}; i < this->number_of_platform_processors; ++i) {
        auto destination = this->platform_apic_id[i];
        if (destination == self) {
            continue;
        }

        if (auto slot = processor_slot(destination)) {
            this->started_by_guest_start_up_ipi[*slot] = true;
        }

        if (start_up_result::needs_hardware ==
            start_up_processor(destination, vector)) {
            // The guest's broadcast cannot be forwarded for one target
            // and swallowed for another, so this target gets its own
            // command. Identical in effect to the broadcast the guest
            // wrote, restricted to the processor that still needs it.
            log("broadcast start-up ipi, apic id {} needs hardware, "
                "vector {}",
                destination,
                vector);

            send_start_up_ipi(destination, vector);
        }
    }

    return true;
}
void hypervisor::intercept_interrupt_command(bool intercept)
{
    // The MSR bitmap is four 1024 byte bitmaps: reads of the low range,
    // reads of the high range, writes of the low range, writes of the high
    // range. The interrupt command register is in the low range.
    constexpr std::size_t write_low_range = 0x800;

    auto bit = arch::x86_64::msr::ia32_x2apic_icr;
    auto & byte = this->msr_bitmap[write_low_range + (bit / 8)];
    auto mask = static_cast<std::uint8_t>(1u << (bit % 8));

    if (intercept) {
        byte |= mask;
    } else {
        byte &= static_cast<std::uint8_t>(~mask);
    }
}
void hypervisor::note_apic_mode(std::size_t cpu)
{
    // IA32_APIC_BASE[EN] is bit 11 and [EXTD] is bit 10, and SDM 13.12.5.1
    // reads the pair as the four states below - the fourth of which,
    // EN=0 with EXTD=1, "is not valid and it is not possible to get into".
    constexpr std::uint64_t apic_base_enabled = 1ull << 11;
    constexpr std::uint64_t apic_base_extended = 1ull << 10;

    auto base = arch::x86_64::rdmsr(arch::x86_64::msr::ia32_apic_base);

    auto mode = apic_mode::disabled;
    if (0 != (base & apic_base_extended)) {
        mode = apic_mode::x2apic;
    } else if (0 != (base & apic_base_enabled)) {
        mode = apic_mode::xapic;
    }

    // Everything below is one processor's decision about machine-wide
    // state, so it is taken under a lock.
    //
    // The state is machine-wide twice over: `observed_apic_mode` is read
    // across every processor, and the MSR bitmap is a **single page**
    // that every processor's VMCS points at - `msr_bitmap` is one array
    // in this class, not one per processor. So `intercept_interrupt_
    // command` is a read-modify-write of a byte another processor may be
    // reading, writing, or having its own VMX operation consult, and it
    // was performed in root operation with nothing holding anything.
    //
    // The case that breaks without this is the one the survey below was
    // written for, and the comment on it named the hazard without
    // covering it: a guest switches its processors to x2APIC one at a
    // time. Two processors doing that at once each write their own slot
    // and then survey, and a processor whose survey ran before the other
    // processor's store became visible computes `any_x2apic` false and
    // *disarms* the interception the other one has just armed. Which of
    // the two unsynchronised writes to the shared byte lands last decides
    // the outcome, and the losing outcome is a processor in x2APIC mode
    // whose interrupt command register is not intercepted - so its
    // start-up IPIs are never seen and the processors it starts are never
    // adopted.
    //
    // The lock is not recursive and nothing under it takes another, which
    // is what makes it safe to hold across `watch_local_apic`: that path
    // reaches the extended page tables, and the page-watch code takes no
    // lock of its own.
    this->apic_mode_lock.lock();
    zpp::scope_exit unlock{[&] { this->apic_mode_lock.unlock(); }};

    if (cpu < max_cpus) {
        this->observed_apic_mode[cpu] = mode;
    }

    // Over every processor, not over the caller. A guest switches its
    // processors to x2APIC one at a time, so during that switch both
    // mechanisms are genuinely in use at once and disarming either would
    // lose interrupt commands from the processors that have not moved yet.
    auto any_x2apic = false;
    auto any_xapic = false;
    for (auto seen : this->observed_apic_mode) {
        any_x2apic = any_x2apic || (apic_mode::x2apic == seen);
        any_xapic = any_xapic || (apic_mode::xapic == seen);
    }

    // Armed only while some processor is in x2APIC mode, which is a
    // correctness matter and not only a cost. The register is an MSR only
    // in that mode - SDM 13.12.1 - so a guest in xAPIC mode writing it is
    // one that should take #GP, and an armed bit would instead exit and
    // have this VMM perform the write in the host, where the #GP has no
    // recovery point and stops the processor.
    intercept_interrupt_command(any_x2apic);

    // And the page, only while some processor still uses it. Reads the
    // base from the calling processor's own MSR, which is right because
    // the page is a single physical address that every processor's local
    // APIC answers at; a machine that gave each processor a different one
    // would need a watch per processor and gets none.
    watch_local_apic(any_xapic);

    // The shape is KVM's. kvm_lapic_set_base in arch/x86/kvm/lapic.c
    // notices any change in either of those two bits and calls
    // set_virtual_apic_mode, and vmx_set_virtual_apic_mode in
    // arch/x86/kvm/vmx/vmx.c then switches on the resulting mode to arm
    // the APIC-access mechanism for xAPIC or the x2APIC MSR bitmap for
    // x2APIC - the same two things, re-derived rather than left as they
    // were set at launch.
}
// extracted 5 definitions
}
