#!/bin/sh
# Harness for the interrupted-event re-queue on the way back to a guest.
#
#   shim/            a stand-in hypervisor.h carrying only the
#                    per-processor event state and the VMCS, so the REAL
#                    resume_guest compiles natively; a diag/log.h with
#                    the pump and the sink policy that path asks about;
#                    and an asm.h whose restore_context comes back
#                    instead of trapping, because resume_guest is
#                    [[noreturn]] and everything worth reading is written
#                    just before it.
#   ../nested_vmx/shim
#                    the vmx/asm.h shim, so the real vmcs.h works against
#                    an in-memory VMCS. This directory comes first on the
#                    include path so the three files above win.
#   harness.cpp      the fake VMCS state and the tests.
#   real.cpp         generated below - the function body cut out of
#                    hypervisor.cpp, byte for byte.
#
# Cut by NAME rather than by line number, the same way tests/local_apic,
# tests/watched_page and tests/ap_start_up do it: the cut then moves with
# the code, and a renamed or deleted function fails the build here instead
# of silently testing nothing.
#
# Built with nested VMX on, because two of the branches under test - the
# level an event belongs to and which of the four entries the processor
# leaves through - do not exist with it off.
#
# Never run clang-format over this file. It reflows a shell script as C++
# and destroys it, exactly as CLAUDE.md records for Markdown.
set -e
cd "$(dirname "$0")"
SRC=${SRC:-"$(cd ../.. && pwd)/hypervisor"}

WANTED='resume_guest event_allowed_on_entry'

{
    echo '// GENERATED by build.sh - do not edit, do not commit.'
    echo '// The body below is cut verbatim out of'
    echo '// hypervisor/src/hypervisor/hypervisor.cpp.'
    echo '#include "zpp/hypervisor/hypervisor.h"'
    echo 'namespace zpp::hypervisor {'
    awk -v wanted="$(echo $WANTED)" '
        BEGIN {
            split(wanted, names, " ");
            for (i in names) { want[names[i]] = 1 }
            copying = 0; found = 0;
        }
        copying == 0 {
            # A definition starts at column zero and names the class.
            # Two shapes appear: the return type on the same line, and
            # the return type on the line above with "hypervisor::" at
            # column zero. The second needs the line above kept.
            line = $0;
            wants_previous = match(line, /^hypervisor::[a-z_]+\(/);
            if (wants_previous ||
                match(line, /^[A-Za-z_].*hypervisor::[a-z_]+\(/)) {
                name = line;
                sub(/^.*hypervisor::/, "", name);
                sub(/\(.*$/, "", name);
                if (name in want) {
                    copying = 1; found++; seen[name] = 1;
                    if (wants_previous) { print previous }
                    print; next;
                }
            }
            previous = $0;
            next;
        }
        { print }
        /^}$/ { copying = 0 }
        END {
            for (n in want) {
                if (!(n in seen)) {
                    printf("#error \"not found in the hypervisor sources: %s\"\n", n);
                }
            }
            printf("// extracted %d definitions\n", found);
        }
    ' "$SRC/src/hypervisor/hypervisor.cpp"
    echo '}'
} > real.cpp

EXTRACTED=$(grep -c '^// extracted' real.cpp || true)
if [ "$EXTRACTED" != "1" ]; then
    echo "extraction failed" >&2
    exit 1
fi
grep -q '#error' real.cpp && { grep '#error' real.cpp >&2; exit 1; }
COUNT=$(sed -n 's/^\/\/ extracted \([0-9]*\) .*/\1/p' real.cpp)
if [ "$COUNT" != "2" ]; then
    echo "expected 2 definitions, extracted $COUNT" >&2
    exit 1
fi
echo "$COUNT definitions extracted"

clang++ -std=c++2c -g -O1 -Wall -Wextra -fno-exceptions -fno-rtti \
    -DZPP_NESTED_VMX=1 \
    -I shim -I ../nested_vmx/shim -I "$SRC/include" -I . \
    harness.cpp real.cpp -o resumeguest
exec ./resumeguest
