// GENERATED by build.sh - do not edit, do not commit.
// The body below is cut verbatim out of
// hypervisor/src/hypervisor/hypervisor.cpp.
#include "zpp/hypervisor/hypervisor.h"
namespace zpp::hypervisor {
bool hypervisor::event_allowed_on_entry(std::uint64_t event) const
{
    // SDM 29.3.1.5, the activity-state and interruptibility-state checks
    // on VM entry (.references/sdm.txt:202612-202628). Transcribed as a
    // predicate rather than open-coded at the one call site, because it
    // is a property of the architecture and the next thing that wants to
    // inject has to ask the same question.
    //
    // Answering "no" is not an error. It means the guest is in a state
    // the event may not be delivered into *yet* - a processor waiting
    // for its start-up IPI, or one inside an STI shadow - and the caller
    // holds the event for a later entry.
    namespace activity = arch::x86_64::vmx::activity_state;

    constexpr std::uint64_t type_shift = 8;
    constexpr std::uint64_t type_mask = 7;
    constexpr std::uint64_t type_external_interrupt = 0;
    constexpr std::uint64_t type_nmi = 2;
    constexpr std::uint64_t type_hardware_exception = 3;
    constexpr std::uint64_t type_other_event = 7;
    constexpr std::uint64_t vector_mask = 0xff;
    constexpr std::uint64_t vector_debug = 1;
    constexpr std::uint64_t vector_machine_check = 18;
    constexpr std::uint64_t vector_pending_mtf = 0;
    constexpr std::uint64_t blocking_by_sti_or_mov_ss = 0x3;

    auto type = (event >> type_shift) & type_mask;
    auto vector = event & vector_mask;
    auto activity_state = this->vmcs.guest_activity_state();

    switch (activity_state) {
    case activity::active:
        // "Active. Any event is allowed."
        break;

    case activity::hlt:
        // "HLT. The only events allowed are ... external interrupt or
        // NMI ... hardware exception and vector 1 or 18 ... other event
        // and vector 0."
        if ((type_external_interrupt != type) && (type_nmi != type) &&
            !((type_hardware_exception == type) &&
              ((vector_debug == vector) ||
               (vector_machine_check == vector))) &&
            !((type_other_event == type) &&
              (vector_pending_mtf == vector))) {
            return false;
        }
        break;

    case activity::shutdown:
        // "Shutdown. Only NMIs and machine-check exceptions are
        // allowed."
        if ((type_nmi != type) && !((type_hardware_exception == type) &&
                                    (vector_machine_check == vector))) {
            return false;
        }
        break;

    case activity::wait_for_start_up_ipi:
        // "Wait-for-SIPI. No events are allowed."
        //
        // The caller drops rather than holds on this one, and the
        // distinction is not arbitrary: the only thing that parks a
        // processor in wait-for-SIPI is an INIT, and an INIT destroys
        // what was pending. KVM's `kvm_vcpu_reset` clears the exception
        // and interrupt queues on the same event. Holding here would
        // deliver, into a processor that has just been reset, an event
        // its previous life was owed.
        return false;

    default:
        // A state the architecture does not define. Refusing is the safe
        // answer: the alternative is an entry the processor rejects,
        // which produces no exit and stops the processor silently.
        return false;
    }

    // "Bit 0 (blocking by STI) and bit 1 (blocking by MOV-SS) must both
    // be 0 if the valid bit ... is 1 and the event type ... has value 0,
    // indicating external interrupt, or value 2, indicating
    // non-maskable interrupt."
    //
    // Note the type restriction, which is easy to lose: an exception may
    // be injected into an STI shadow, and only these two may not.
    if ((type_external_interrupt == type) || (type_nmi == type)) {
        if (0 != (this->vmcs.read(arch::x86_64::vmx::vmcs::field::
                                      guest_interruptibility_state) &
                  blocking_by_sti_or_mov_ss)) {
            return false;
        }
    }

    return true;
}
void hypervisor::resume_guest(arch::x86_64::context & context,
                              arch::x86_64::vmx::exit_reason full_reason,
                              bool advance_rip)
{
    auto & vmcs = this->vmcs;

    // Put back the event whose delivery the exit interrupted.
    //
    // The processor clears the entry-interruption field as it begins a
    // delivery, so an exit taken *during* one leaves nothing to resume
    // from: the only record is the interrupted-event field, and the next
    // entry overwrites that too. An event not put back here is destroyed
    // silently, and the guest that injected it cannot tell the difference
    // from one that arrived.
    //
    // Measured on the rig before this existed: nine events destroyed in a
    // single boot, every one of them interrupted by an EPT violation
    // against the second-level guest's lazily built shadow table - two
    // inter-processor interrupts at vector 0x2f, five clock interrupts at
    // 0xd1, and three page faults. The two at 0x2f are how a halted
    // virtual processor is woken, which is why the machine stopped with
    // every processor halted and nothing pending.
    //
    // KVM does the same thing in `vmx_complete_interrupts`
    // (.references/kvm/vmx.c:7488), which re-queues the vector, the error
    // code (:7142-7146) and the software-event length (:7139, :7149).
    //
    // Not done where the exit is reflected: there the interrupted event
    // is copied into the guest hypervisor's own VMCS and becomes its
    // business, and putting it back here as well would deliver it twice.
    //
    // SWITCHED OFF, and the switch is the whole point of this constant.
    // `git bisect` over seven rig boots, good `1975400`, bad `02c747e` -
    // the commit that added this - named it as the first commit at which
    // the guest hypervisor stops bringing up its application processors.
    // The verdict each boot was whether any of `cpu 0x1` .. `cpu 0x7`
    // reaches `guest vmxon` within about three minutes: seven of them do
    // at `1975400` and none does at `02c747e`, reproducibly, on the same
    // launcher and the same Windows installation.
    //
    // Two defects are visible by inspection and either could be it, so
    // neither is claimed as the cause without a measurement that
    // separates them:
    //
    // - the write below is unconditional, so it overwrites an
    //   entry-interruption field the exit handler had already staged for
    //   this entry - an injected fault, say - rather than yielding to it;
    // - `pending_event[cpu]` is cleared only when it is re-injected, so
    //   an event deferred because it belonged to the other level is held
    //   indefinitely and then delivered into some later unrelated entry.
    //
    // BOTH DEFECTS ARE FIXED AND IT IS BACK ON. See the two branches
    // below marked "defect 1" and "defect 2".
    //
    // What settled it was not inspection. The monitor trap flag armed on
    // every entry that injects `0xd1` - the vector the root partition's
    // `SINT3` carries - exits after one retired instruction, and on all
    // eight processors the first landing was an EPT violation with the
    // instruction pointer **unmoved**. Delivery reads the interrupt
    // descriptor table and pushes five words on the guest's stack before
    // reaching the handler, and both go through the extended page
    // tables, so it faults there against the lazily built shadow. With
    // this off the event was then destroyed, the handler never ran, the
    // end-of-message register was never written, and Hyper-V dropped the
    // timer and halted every processor behind it. BACKLOG.md carries the
    // whole chain.
    //
    // That is the same failure the paragraph above measured from the
    // other end - "five clock interrupts at 0xd1" - found again months
    // later by a different measurement.
    // Expressible as a build option, `-DZPP_REQUEUE_INTERRUPTED_EVENTS`,
    // for the same reason the launcher makes the processor count one:
    // "did this come from the re-queue" then costs one boot instead of an
    // argument. It defaulted to `false` for a long time and the comment
    // above says why; it is `true` now and BACKLOG.md says why.
    constexpr bool requeue_interrupted_events =
        (0 != ZPP_REQUEUE_INTERRUPTED_EVENTS);

    if constexpr (!requeue_interrupted_events) {
        (void)0;
    } else if (auto slot = vmcs.vpid();
               (0 != slot) && (slot <= max_cpus)) {
        auto cpu = slot - 1;
        constexpr std::uint64_t injection_valid = 1ull << 31;

        auto staged =
            vmcs.read(arch::x86_64::vmx::vmcs::field::
                          vm_entry_interruption_information_field);

        // Defect 1: yield to an event this exit's own handler staged.
        //
        // The write below used to be unconditional, so a re-queue
        // silently replaced a fault the handler had just decided to
        // inject - the general protection fault for a locked MSR, say.
        // The exit's own event wins: it is the processor's account of
        // what the guest just did, and delivering it is the whole reason
        // the exit was handled that way. The interrupted one stays held
        // and goes in on a later entry, which is what being held is for.
        //
        // The same test is already spelled twice in this file, at the
        // invalid-opcode injection and the MSR fault, both reading the
        // field's valid bit for exactly this reason.
        if (this->pending_event[cpu] &&
            (0 != (staged & injection_valid))) {
            this->events_yielded[cpu] = this->events_yielded[cpu] + 1;

            // Only into the guest it was being delivered to. A guest
            // hypervisor's VMLAUNCH is an exit like any other, so an exit
            // that interrupted a delivery to it can be followed straight
            // away by an entry into *its* guest - and putting the event
            // back there would hand one level's interrupt to the other.
            // Held instead until that guest runs again.
        } else if (this->pending_event[cpu] &&
                   (this->pending_event_l2[cpu] !=
                    this->running_l2[cpu])) {
            this->events_deferred[cpu] = this->events_deferred[cpu] + 1;

            // Defect 2: the guest it belonged to is gone.
            //
            // Being held across an entry into the other level is normal
            // and the branch above is what does it. Being held across a
            // VMPTRLD of a different region is not: that is a different
            // second-level guest, and the event is one its predecessor
            // was owed. Delivering it there is delivering a vector into
            // a guest that never had it pending - the worst shape of
            // this bug, because it arrives long after the exit that
            // produced it and nothing connects the two.
            //
            // Discarded rather than held for ever, and counted, because
            // an event whose guest is gone has no later entry to wait
            // for and a silent leak here would look exactly like the
            // destruction this whole path exists to prevent.
        } else if (this->pending_event[cpu] &&
                   this->pending_event_l2[cpu] &&
                   (this->pending_event_vmcs[cpu] !=
                    this->guest_current_vmcs[cpu])) {
            this->pending_event[cpu] = 0;
            this->events_discarded[cpu] = this->events_discarded[cpu] + 1;
            // Defect 3, which neither of the two named on the switch
            // covered and which is what the first re-run of this found:
            // **the entry state has to allow the event at all.**
            //
            // A re-queue writes the entry-interruption field after the
            // rest of the entry has been decided, so unlike an injection
            // the handler chose, nothing above it has checked the state
            // it is landing in. SDM 29.3.1.5 (`sdm.txt:202612-202621`)
            // makes three of those a consistency check, and a failed
            // check is a VM entry failure - which produces **no exit at
            // all** and is exactly as silent as the destruction this
            // path exists to prevent.
            //
            // - "Wait-for-SIPI. No events are allowed." This is the one
            //   that matters: an application processor waiting for its
            //   start-up IPI is precisely a processor in that state, and
            //   re-queueing into it fails every entry. Turning this path
            //   on without the check reproduced the original regression
            //   exactly - one processor of eight reaching `guest vmxon`,
            //   which is the same verdict `git bisect` recorded against
            //   `02c747e` over seven boots.
            // - "Shutdown. Only NMIs and machine-check exceptions are
            //   allowed."
            // - "HLT. The only events allowed are ... external interrupt
            //   or NMI ... hardware exception and vector 1 or 18 ...
            //   other event and vector 0."
            //
            // And SDM 29.3.1.5 again (`sdm.txt:202627`): blocking by STI
            // and by MOV SS must both be 0 when the injected event is an
            // external interrupt or an NMI.
            //
            // Held rather than forced in every case. Clearing the
            // interruptibility bits would also satisfy the processor -
            // SDM 27.3.1.5 (`sdm.txt:203115`) says an injecting entry
            // leaves no such blocking regardless, and KVM's
            // `vmx_clear_interrupt_shadow` does exactly that - but that
            // is guest state this VMM did not write, and holding costs
            // only a later entry. An STI shadow lasts one instruction.
            //
            // Held, not dropped - with one exception, below. The state
            // that refuses the event is the state the guest is in now,
            // and the reason to keep the event is that the guest will
            // leave it.
            //
            // Wait-for-SIPI is the exception, and it is dropped rather
            // than held. The only thing that parks a processor there is
            // an INIT, and an INIT **destroys what was pending** - KVM's
            // `kvm_vcpu_reset` clears the exception and interrupt queues
            // on the same event. Holding would deliver, into a processor
            // that has just been reset, an event its previous life was
            // owed.
        } else if (this->pending_event[cpu] &&
                   !event_allowed_on_entry(this->pending_event[cpu])) {
            this->events_refused_by_state[cpu] =
                this->events_refused_by_state[cpu] + 1;

            if (arch::x86_64::vmx::activity_state::wait_for_start_up_ipi ==
                vmcs.guest_activity_state()) {
                this->pending_event[cpu] = 0;
                this->events_discarded[cpu] =
                    this->events_discarded[cpu] + 1;
            }
        } else if (auto event = this->pending_event[cpu]; 0 != event) {
            constexpr std::uint64_t error_valid = 1ull << 11;
            constexpr std::uint64_t type_mask = 7ull << 8;
            constexpr std::uint64_t type_software_interrupt = 4ull << 8;
            constexpr std::uint64_t type_privileged_software = 5ull << 8;
            constexpr std::uint64_t type_software_exception = 6ull << 8;
            constexpr std::uint64_t type_nmi = 2ull << 8;

            if (0 != (event & error_valid)) {
                vmcs.write(arch::x86_64::vmx::vmcs::field::
                               vm_entry_exception_error_code,
                           this->pending_event_error[cpu]);
            }

            // A software event resumes at the instruction after the one
            // that raised it, so the processor has to be told how long
            // that instruction was. A hardware one ignores the field.
            if (auto type = event & type_mask;
                (type_software_interrupt == type) ||
                (type_privileged_software == type) ||
                (type_software_exception == type)) {
                vmcs.write(arch::x86_64::vmx::vmcs::field::
                               vm_entry_instruction_length,
                           this->pending_event_length[cpu]);
            }

            // An NMI put back has to be put back into a state that
            // accepts it. SDM 29.3.1.5: blocking by NMI must be 0 when
            // the injected event is an NMI and the "virtual NMIs"
            // VM-execution control is 1. This VMM does not ask for that
            // control, but `build_vmcs02` merges it from a guest
            // hypervisor that does - so the entry it would refuse is a
            // second-level one, and refusing it produces no exit at all.
            //
            // Cleared rather than held, unlike the STI shadow above, and
            // for a reason that does not apply there: the blocking is
            // the architecture's record that an NMI is *in progress*,
            // and the NMI being put back is that same one. Waiting for
            // it to clear is waiting for the IRET of a handler that
            // never ran. KVM clears it unconditionally on this path,
            // `vmx.c:7130`.
            if (type_nmi == (event & type_mask)) {
                vmcs.guest_interruptibility_state(
                    vmcs.guest_interruptibility_state() &
                    ~arch::x86_64::vmx::interruptibility_state::
                        blocking_by_nmi);
            }

            // Masked, not copied. The interrupted-event field this was
            // read from carries bit 13, "nested exception", which SDM
            // 29.2.1.3 makes legal in the *entry* field only on a
            // processor enumerating FRED. Copying the word verbatim
            // hands the processor a reserved bit and the entry is
            // refused - silently, like every other failed check here.
            vmcs.write(arch::x86_64::vmx::vmcs::field::
                           vm_entry_interruption_information_field,
                       event & arch::x86_64::vmx::vm_entry_interruption::
                                   defined_bits);

            this->pending_event[cpu] = 0;
            this->events_requeued[cpu] = this->events_requeued[cpu] + 1;
        }
    }

    // Move a few records out of the ring on the way back to the
    // guest.
    //
    // Here rather than on a timer, because this is the only place
    // that is guaranteed to run while a guest is alive and is
    // already a context where taking microseconds is normal. The
    // budget is four records, so this is a trickle that keeps up
    // with a guest rather than a flush - a flush belongs in the halt
    // paths, where there is no guest left to delay.
    //
    // It compiles to nothing when the facility is off: pump::run
    // is `if constexpr (!enabled) return;` and every sink behind it
    // folds away with it.
    diag::pump::run();

    // Keep the timer running while the channel is live, because
    // otherwise nothing happens at all.
    //
    // Measured, and it is the finding that decides how a continuous
    // log has to work: a steadily running Windows takes about
    // fifteen hundred exits on its busiest processor and a hundred
    // and sixty on the others - not millions. This VMM intercepts
    // very little, which is the point of it, and the consequence is
    // that the write path is reached almost never. A log driven by
    // guest exits is a log that stops the moment the guest settles.
    //
    // The preemption timer manufactures the exits instead, at an
    // interval this side chooses. That is a real cost - an exit the
    // guest would not otherwise have taken - so it is only armed
    // while there is a channel to feed.
    if constexpr (diag::policy_of(diag::sink::esp_blocks).present) {
        arm_controller_poll(diag::esp_block_sink::ready());
    }

    // A heartbeat, so the channel has something to carry.
    //
    // Without it the log is silent whenever nothing goes wrong, which
    // is most of the time - and a silent channel is
    // indistinguishable from a broken one to whoever is reading the
    // disk from another machine. That distinction is the whole point
    // of the channel, so it emits a line periodically whether or not
    // anything happened, and the line carries the two things worth
    // knowing about a guest that is merely alive: which processor
    // this is and how many exits it has taken.
    //
    // Counted rather than timed, because a count is free and reading
    // the time stamp counter on every exit is not. The interval is
    // large enough that the cost is nothing and small enough that a
    // reader sees movement within a second on any busy guest.
    if constexpr (diag::enabled) {
        // A proof of life, deliberately slow.
        //
        // This record exists only so an idle channel can be told
        // apart from a dead one, and it is the one record this side
        // manufactures rather than observes. That makes its rate a
        // direct tax on the region: the sink flushes a partly filled
        // block once staged_deadline_ticks passes, so a heartbeat
        // faster than a block fills turns every 128-byte record into
        // a 4096-byte write.
        //
        // Measured at one per eight ticks: 152 blocks a second, one
        // record in each, wrapping the 64 MB region every seven
        // minutes and writing 620 KB/s to the medium for nothing.
        // At one per thousand ticks it is 4 KB/s and the region holds
        // about four and a half hours.
        //
        // The freshness the deadline buys is not lost by slowing this
        // down, because it applies to real records too: anything the
        // guest actually causes still reaches the medium within
        // staged_deadline_ticks of being written. Only the synthetic
        // traffic is throttled, and an idle guest now writes nothing
        // at all - which is the correct behaviour, not a regression.
        constexpr std::uint64_t heartbeat_exits = 1000;
        auto cpu = vmcs.vpid();
        if ((0 != cpu) && (cpu <= max_cpus)) {
            auto & seen = this->heartbeat_exits_seen[cpu - 1];
            if (0 == (++seen % heartbeat_exits)) {
                diag::log<diag::severity::trace>(
                    "cpu {} alive, {} exits", cpu - 1, seen);
            }
        }
    }

    // Update RIP, unless nothing was executed. For an INIT signal or
    // a start-up IPI the instruction length field holds nothing
    // meaningful, and both handlers have already put RIP where the
    // processor is meant to resume - adding to it would land the
    // guest a few bytes into its own entry point.
    if (advance_rip) {
        context.rip += vmcs.vm_exit_instruction_length();
        vmcs.guest_rip(context.rip);
    }

    // Record what is about to be resumed, now that the handlers have
    // had their say.
    record_exit(full_reason, context);

    // Counted here, at the last point before control leaves this
    // handler, so a frozen exit count can be read two ways round.
    if (auto slot = vmcs.vpid(); (0 != slot) && (slot <= max_cpus)) {
        this->resumes_reached[slot - 1] =
            this->resumes_reached[slot - 1] + 1;

        // The activity state only from this VMM's own VMCS, because it is
        // consumed rather than merely read: start_up_processor decides
        // whether to deliver a guest's start-up IPI by it, and a
        // second-level guest's activity state answers a different
        // question about a different virtual processor. Left at vmcs01's
        // last value while one runs, which is the first-level guest's
        // state and is what the guest hypervisor's own processor is
        // actually in. A second-level guest waiting for a start-up IPI is
        // held by enter_or_park_l2 and recorded in `l2_activity_state`,
        // which is the record start_up_processor asks alongside this one.
        //
        // RIP and CS are not gated, deliberately: nothing consumes them,
        // they exist to be read from a debugger, and the address a
        // second-level guest is at is the more useful of the two answers.
        auto in_l2 = false;
        if constexpr (nested_vmx::enabled) {
            in_l2 = this->running_l2[slot - 1];
        }

        if (!in_l2) {
            this->resume_activity_state[slot - 1] =
                vmcs.guest_activity_state();
        }

        this->resume_guest_rip[slot - 1] = vmcs.guest_rip();
        this->resume_guest_cs[slot - 1] = vmcs.guest_cs_selector();
    }

    // Whether this processor has been out of VMX operation and back
    // since the last entry, which only the sleep quiesce does. Its
    // return leaves the launch state clear, and VMRESUME requires
    // launched (SDM 27.1) - so that one case has to leave through
    // VMLAUNCH instead. Consumed here, so the next exit resumes.
    auto relaunch = false;
    if (auto slot = vmcs.vpid(); (0 != slot) && (slot <= max_cpus)) {
        relaunch = this->relaunch_after_sleep[slot - 1];
        this->relaunch_after_sleep[slot - 1] = false;
    }

    // Which entry this processor leaves through, which is three
    // questions rather than one.
    //
    // A processor running a second-level guest goes back to it through
    // the nested pair, whose failure path recovers instead of halting -
    // a guest hypervisor's VMLAUNCH is a guest instruction and no guest
    // instruction may stop a processor. Which of the two depends on
    // vmcs02's own launch state, which SDM 29 step 5 makes "launched"
    // only after an entry has passed every check.
    //
    // Otherwise it is the ordinary pair, and VMLAUNCH only where this
    // processor has been out of VMX operation and back since its last
    // entry - see relaunch above.
    auto entry = relaunch ? arch::x86_64::vmx::vmlaunch
                          : arch::x86_64::vmx::vmresume;

    if constexpr (nested_vmx::enabled) {
        if (auto slot = vmcs.vpid(); (0 != slot) && (slot <= max_cpus) &&
                                     this->running_l2[slot - 1]) {
            entry = this->vmcs02_launched[slot - 1]
                        ? arch::x86_64::vmx::nested_vmresume
                        : arch::x86_64::vmx::nested_vmlaunch;
        }
    }

    // The mirror of the launch: the guest's registers are put back
    // and the last thing executed in host mode is the resume itself.
    context.rip = reinterpret_cast<std::uint64_t>(entry);
    arch::x86_64::restore_context(&context);
    std::unreachable();
}
// extracted 2 definitions
}
