#!/bin/sh
# Compiles and runs the nested EPT tests.
#
# Two tiers, and the script exists because of the second.
#
# Tier one is static_asserts over nested_ept.h - the walker, the
# permission composition, the reflected exit qualification. Those are
# pure, so the compile *is* the run, the same arrangement as
# check-decoder.sh beside it.
#
# Tier two is the shadow table pool, the shadow walk, the second-level
# fault decision and the EPT-pointer check. Those are members of
# `hypervisor` writing into arrays that are megabytes of that class, so
# they cannot be constant-evaluated - they run from main and report a
# count. What this script adds is that none of them is *modelled*: the
# real bodies are cut out of nested_ept.cpp and nested_entry.cpp below,
# by name where they are whole functions and by anchor where they are
# fragments inside one, and compiled against a stand-in `hypervisor` the
# test file supplies. tests/watched_page does the same thing for the same
# reason, and the reason is that extraction fails loudly when the code
# moves, where a transcription silently goes on testing itself.
#
# Worth having beyond the usual reasons: this is the only verification of
# any part of nested VMX that does not need hardware. Everything else in
# it - the vmcs02, the reflection, the shadow tables in place - can
# currently only be read.
#
# The tests were checked for teeth rather than assumed to have them.
# Deliberately broken, one at a time, and reverted:
#
#   - composing with a union instead of an intersection fails
#     composition_is_the_normalised_intersection,
#     composition_grants_nothing_new and 232 of the fault-owner rows;
#   - consulting our own tables before the guest hypervisor's fails
#     a_page_the_guest_hypervisor_watches and 96 fault-owner rows;
#   - letting the shadow walk descend into a large leaf reproduces the
#     original symptom, error 4, in
#     a_large_leaf_is_dropped_for_a_smaller_one;
#   - releasing a slot without returning its tables fails
#     releasing_a_slot_returns_its_tables;
#   - dropping the accessed-and-dirty test from the EPT-pointer checks
#     fails the_eptp_checks_hold.
#
# Never run clang-format over this file. It reflows a shell script as C++
# and destroys it, exactly as CLAUDE.md records for Markdown.
set -e

here=$(dirname "$0")
root=$here/../..

: "${CXX:=clang++}"

out=$(mktemp -d)
trap 'rm -rf "$out"' EXIT

nested_ept=$root/hypervisor/src/hypervisor/nested_ept.cpp
nested_entry=$root/hypervisor/src/hypervisor/nested_entry.cpp
hypervisor_h=$root/hypervisor/include/zpp/hypervisor/hypervisor.h

inc=$out/nested-ept-extracted.inc

# The two pool constants the stand-in class spells as literals. Pinned
# here rather than derived, because deriving them needs nested_vmx.h and
# the ZPP_NESTED_VMX switch, and a stand-in that silently disagreed with
# the real pool would make every pool test meaningless.
pin() {
    if ! grep -q "$1" "$2"; then
        echo "check-nested-ept: not found in $2: $1" >&2
        exit 1
    fi
}

pin 'shadow_ept_tables_per_cpu =' "$hypervisor_h"
pin 'nested_vmx::enabled ? 96 : 1' "$hypervisor_h"
pin 'shadow_ept_slots =' "$hypervisor_h"
pin 'nested_vmx::enabled ? 4 : 1' "$hypervisor_h"
pin 'shadow_table_free = 0' "$hypervisor_h"

{
    echo '// GENERATED by check-nested-ept.sh - do not edit, do not commit.'
    echo '// Cut verbatim out of hypervisor/src/hypervisor/nested_ept.cpp'
    echo '// and hypervisor/src/hypervisor/nested_entry.cpp.'
    echo 'namespace zpp::hypervisor {'

    # The whole anonymous namespace of nested_ept.cpp: the using
    # declarations, entries_per_table, the page-size shifts and
    # leaf_result. Taken wholesale rather than by name because the
    # functions below name all of it, and a copy of it here would be the
    # transcription this file exists to avoid.
    awk '
        /^namespace$/ { inside = 1 }
        inside { print }
        /^} \/\/ namespace$/ {
            if (inside) { inside = 0; preamble++ }
        }
        END {
            if (!preamble) {
                print "#error \"nested_ept.cpp anonymous namespace not found\""
            }
        }
    ' "$nested_ept"

    # The three whole functions. Matched at column zero on a line naming
    # the class, with the lines since the last blank one printed ahead of
    # it so a return type on its own line comes too.
    awk -v wanted="shadow_ept_table shadow_ept_entry release_shadow_slot" '
        BEGIN {
            split(wanted, names, " ")
            for (i in names) { want[names[i]] = 1 }
            copying = 0; found = 0; n = 0
        }
        copying == 0 {
            if ($0 == "") { n = 0; next }
            if (($0 ~ /^[A-Za-z_]/) && ($0 ~ /hypervisor::[a-z_]+\(/)) {
                name = $0
                sub(/^.*hypervisor::/, "", name)
                sub(/\(.*$/, "", name)
                if (name in want) {
                    for (i = 1; i <= n; ++i) { print buf[i] }
                    print
                    copying = 1; found++; seen[name] = 1; n = 0
                    next
                }
            }
            buf[++n] = $0
            next
        }
        { print }
        /^}$/ { copying = 0; n = 0 }
        END {
            for (nm in want) {
                if (!(nm in seen)) {
                    printf("#error \"not found in nested_ept.cpp: %s\"\n", nm)
                }
            }
            printf("// extracted %d definitions\n", found)
        }
    ' "$nested_ept"

    # The EPT-pointer checks, which live inside build_vmcs02 rather than
    # in a function of their own. Anchored on the first constant of the
    # block and on the call that follows it, so a reordering fails the
    # extraction rather than quietly shrinking it.
    echo 'std::expected<void, zpp::error>'
    echo 'hypervisor::eptp_accepted(std::uint64_t eptp12)'
    echo '{'
    echo '    namespace vmx_msr = arch::x86_64::vmx::msr;'
    awk '
        /constexpr std::uint64_t eptp_memory_type_mask/ {
            inside = 1; starts++
        }
        /auto shadow_pointer = shadow_ept_pointer_for\(cpu, eptp12\);/ {
            if (inside) { inside = 0; ends++ }
        }
        inside { print }
        END {
            if ((starts != 1) || (ends != 1)) {
                print "#error \"the eptp checks moved in nested_entry.cpp\""
            }
        }
    ' "$nested_entry"
    echo '    return {};'
    echo '}'

    # The composed branch of on_l2_ept_fault: the access decode, the
    # permits predicate, and the two tests in the order they are applied.
    # Anchored on the first line of the decode and on the comment that
    # begins the install path.
    echo 'hypervisor::l2_exit_outcome hypervisor::l2_fault_decision('
    echo '    std::size_t cpu,'
    echo '    std::uint64_t reason,'
    echo '    guest_context & context,'
    echo '    std::uint64_t guest_physical,'
    echo '    std::uint64_t qualification,'
    echo '    const arch::x86_64::vmx::ept_walk_result & guest_walk,'
    echo '    const arch::x86_64::vmx::ept_composition & composition)'
    echo '{'
    awk '
        /auto access_read = 0 != \(qualification/ { inside = 1; starts++ }
        /\/\/ Both levels permit it, so the shadow is behind/ {
            if (inside) { inside = 0; ends++ }
        }
        inside { print }
        END {
            if ((starts != 1) || (ends != 1)) {
                print "#error \"the l2 fault decision moved in nested_entry.cpp\""
            }
        }
    ' "$nested_entry"
    echo '    // Fell through both tests: nothing refused the access, so'
    echo '    // the real function installs the mapping from here.'
    echo '    return l2_exit_outcome::deferred;'
    echo '}'

    echo '}'
} > "$inc"

extracted=$(sed -n 's|^// extracted \([0-9]*\) .*|\1|p' "$inc")
if [ "$extracted" != "3" ]; then
    echo "check-nested-ept: expected 3 definitions, extracted $extracted" >&2
    exit 1
fi

if grep -q '#error' "$inc"; then
    grep '#error' "$inc" >&2
    exit 1
fi

"$CXX" -std=c++2c -Wall -Wextra -Werror \
    -I "$root/hypervisor/include" \
    -I "$out" \
    "$here/nested-ept-test.cpp" \
    -o "$out/nested-ept-test"

"$out/nested-ept-test"
