#!/bin/sh
# Builds and runs the freestanding C runtime harness: the heap, the
# string and memory primitives, scope_exit, the allocator and the
# container aliases, zpp::error, and the init/fini array machinery.
#
#   real.cpp     generated below - crt.cpp with two things dropped, and
#                nothing else changed.
#   harness.cpp  renames the C-linkage names, includes real.cpp, and
#                asserts against it.
#
# Why crt.cpp cannot simply be compiled and linked here, which is the
# whole difficulty of this harness. It is a *replacement* C runtime: it
# defines memcpy, memmove, memset, memcmp and strlen with C linkage, the
# whole __cxa_* ABI, __dso_handle, and every operator new and operator
# delete. Linked into a hosted binary each of those preempts the host's,
# and three separate things break:
#
#   - the mem* differential has no oracle left, because the host's
#     memcpy and ours would be the same function,
#   - our __cxa_atexit would swallow the host runtime's own
#     registrations, and __dso_handle collides with the one the platform
#     already defines,
#   - replacing global operator new routes *every* allocation in the
#     process through the 20 MB arena, including allocations made by the
#     standard library's own initializers, which run before main and so
#     before zpp::crt::init::main() has brought the heap up. That is
#     precisely the trap CLAUDE.md documents: allocate before init and
#     the heap returns null and operator new calls __builtin_trap(). The
#     harness would die at start-up, on the host, for a reason that says
#     nothing about the hypervisor.
#
# So harness.cpp #defines the C-linkage names to zpp_test_* before
# including real.cpp - after including every header crt.cpp includes, so
# no macro is ever live while a system header is being parsed - and
# build.sh drops from real.cpp the only two things a #define cannot
# rename:
#
#   - the twenty operator new / operator delete definitions. 'operator'
#     is a keyword and cannot be macro renamed, and see above for why
#     keeping them is not an option. The three static helpers they call -
#     allocate_or_trap, allocate_aligned_or_trap, deallocate_aligned -
#     are *kept*, so the over-alignment logic is still tested directly,
#     which is where the interesting arithmetic lives.
#
#   - the six extern declarations of __preinit_array_start and friends.
#     These are declared as arrays of unknown bound, and the loops walk
#     from start to end by increment, so a hosted stand-in has to place
#     the two symbols in one contiguous object. No portable C++ can do
#     that - two separate arrays may be laid out in either order, and on
#     Linux those names are linker synthesized and are not ours to
#     define anyway. Dropping the declarations lets harness.cpp declare
#     them as plain pointers instead, which is the same type the loops
#     deduce with auto and lets a test aim them at whatever it likes.
#
# Both cuts are by pattern and both counts are checked below, for the
# reason tests/watched_page gives for cutting by name: the cut moves
# with the code, and a renamed or deleted definition fails the build here
# rather than silently testing nothing.
#
# Native, no emulator and no target. All of this is pure logic and none
# of it had any coverage before.
#
# Never run clang-format over this file. It reflows a shell script as C++
# and destroys it, exactly as CLAUDE.md records for Markdown.
set -e
cd "$(dirname "$0")"
SRC=${SRC:-"$(cd ../.. && pwd)/hypervisor"}

: "${CXX:=clang++}"

{
    echo '// GENERATED by build.sh - do not edit, do not commit.'
    echo '// hypervisor/src/crt/crt.cpp, verbatim, less the allocation'
    echo '// operators and the linker supplied array declarations.'
    awk '
        BEGIN { copying = 1 }
        copying == 0 { if ($0 == "}") { copying = 1 } next }
        /^extern void \(\*__[a-z_]+_array_(start|end)\[\]\)\(\);$/ {
            declarations++; next
        }
        /^void \* operator new/ || /^void operator delete/ {
            operators++; copying = 0; next
        }
        { print }
        END {
            printf("// dropped %d declarations, %d operators\n",
                   declarations, operators);
        }
    ' "$SRC/src/crt/crt.cpp"
} > real.cpp

DROPPED=$(sed -n 's|^// dropped \([0-9]*\) declarations, \([0-9]*\) operators$|\1 \2|p' real.cpp)
if [ "$DROPPED" != "6 20" ]; then
    echo "extraction failed: dropped [$DROPPED], expected [6 20]" >&2
    echo "crt.cpp changed shape - re-read build.sh before adjusting" >&2
    exit 1
fi
echo "dropped $DROPPED (declarations, allocation operators) from crt.cpp"

"$CXX" -std=c++2c -g -O0 -Wall -Wextra -Werror \
    -fno-exceptions -fno-rtti \
    -I "$SRC/include" -I . \
    harness.cpp "$SRC/src/crt/heap.cpp" -o crt

exec ./crt
