include ../environment.config

CLANG_TARGET := $(ZPP_TARGET_TYPE)-pc-win32-msvc

ifeq ($(ZPP_TARGET_TYPE), x86_64)
	MICROSOFT_DEFINES := -D_MT -D_WIN32 -D_WIN64 -D_AMD64_
	VISUAL_STUDIO_PROCESSOR := x64
	WINDOWS_KITS_PROCESSOR := x64
	EDK2_PROCESSOR := X64
else
$(error Unsupported target)
endif

EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

VISUAL_STUDIO_ROOT := $(subst $(SPACE),+,$(VISUAL_STUDIO_ROOT))
WINDOWS_KITS_ROOT := $(subst $(SPACE),+,$(WINDOWS_KITS_ROOT))
EDK2_ROOT := $(subst $(SPACE),+,$(EDK2_ROOT))

VISUAL_STUDIO_INCLUDES := $(VISUAL_STUDIO_ROOT)/include

WINDOWS_KITS_INCLUDES := \
	$(WINDOWS_KITS_ROOT)/Include/$(WINDOWS_KITS_VERSION)/ucrt \
	$(WINDOWS_KITS_ROOT)/Include/$(WINDOWS_KITS_VERSION)/shared

EDK2_INCLUDES := $(EDK2_ROOT)/MdePkg/Include

ENVIRONMENT_INCLUDES := \
	$(EDK2_INCLUDES) \
	$(EDK2_INCLUDES)/$(EDK2_PROCESSOR) \
	$(WINDOWS_KITS_INCLUDES) \
	$(VISUAL_STUDIO_INCLUDES)

ENVIRONMENT_INCLUDES := $(patsubst %, -isystem %, $(ENVIRONMENT_INCLUDES))
ENVIRONMENT_INCLUDES := $(subst +,$(SPACE),$(ENVIRONMENT_INCLUDES))

ENVIRONMENT_FLAGS := \
	-nostdinc \
	-nostdlib \
	-D_CRT_SECURE_NO_WARNINGS \
	-D_CRT_SECURE_NO_DEPRECATE \
	-D_NO_CRT_STDIO_INLINE \
	$(MICROSOFT_DEFINES) \
	-U__GNUC__ \
	-U__gnu_linux__ \
	-U__GNUC_MINOR__ \
	-U__GNUC_PATCHLEVEL__ \
	-U__GNUC_STDC_INLINE__

ENVIRONMENT_LINK_FLAGS := \
	-fuse-ld=lld \
	-Wl,-ignore:4217

ifeq ($(OS), Windows_NT)
CLANG := $(LLVM_ROOT)/bin/clang -target $(CLANG_TARGET)
CLANGXX := $(LLVM_ROOT)/bin/clang++ -target $(CLANG_TARGET)
else
CLANG := clang -target $(CLANG_TARGET)
CLANGXX := clang++ -target $(CLANG_TARGET)
endif

ZPP_CC := \
	$(CLANG) \
	$(ENVIRONMENT_INCLUDES) \
	$(ENVIRONMENT_FLAGS)

ZPP_CXX := \
	$(CLANGXX) \
	$(ENVIRONMENT_INCLUDES) \
	$(ENVIRONMENT_FLAGS)

ZPP_AR := ar
ZPP_AS := $(ZPP_CC)
ZPP_LINK := \
	$(CLANGXX) \
	$(ENVIRONMENT_LINK_FLAGS)

