#!/bin/sh
# Differential harness for the watched-page write path.
#
#   shim/            a stand-in hypervisor.h carrying only what the
#                    watched-page path touches, so the REAL
#                    on_ept_violation, carry_out_guest_instruction,
#                    filter_local_apic_write and on_local_apic_write
#                    compile natively on arm64 macOS.
#   ../nested_vmx/shim
#                    the asm.h, vmx/asm.h and diag/log.h shims, shared
#                    with the other two harnesses. This directory comes
#                    first on the include path so its hypervisor.h wins.
#   harness.cpp      the fake guest memory, the fake VMCS and the tests.
#   real.cpp         generated below - the function bodies cut out of
#                    hypervisor.cpp, byte for byte.
#
# The other two harnesses compile a whole source file. This one cannot:
# hypervisor.cpp is ten thousand lines and reaches the whole VMM, so the
# functions under test are cut out of it by NAME rather than by line
# number. Extracting by name is what keeps this honest - the cut moves
# with the code, and a renamed or deleted function fails the build here
# instead of silently testing nothing. The count is checked below for the
# same reason.
#
# Never run clang-format over this file. It reflows a shell script as C++
# and destroys it, exactly as CLAUDE.md records for Markdown.
set -e
cd "$(dirname "$0")"
SRC=${SRC:-"$(cd ../.. && pwd)/hypervisor"}

WANTED='watch_guest_page_writes unwatch_guest_page read_guest_word
        carry_out_guest_instruction apply_guest_store on_ept_violation
        on_monitor_trap_flag filter_local_apic_write on_local_apic_write'

{
    echo '// GENERATED by build.sh - do not edit, do not commit.'
    echo '// The bodies below are cut verbatim out of'
    echo '// hypervisor/src/hypervisor/hypervisor.cpp.'
    echo '#include "zpp/hypervisor/hypervisor.h"'
    echo 'namespace zpp::hypervisor {'
    awk -v wanted="$(echo $WANTED)" '
        BEGIN {
            split(wanted, names, " ");
            for (i in names) { want[names[i]] = 1 }
            copying = 0; found = 0;
        }
        copying == 0 {
            # A definition starts at column zero and names the class.
            if (match($0, /^[A-Za-z_].*hypervisor::[a-z_]+\(/)) {
                name = $0;
                sub(/^.*hypervisor::/, "", name);
                sub(/\(.*$/, "", name);
                if (name in want) {
                    copying = 1; found++; seen[name] = 1;
                    print; next;
                }
            }
            next;
        }
        { print }
        /^}$/ { copying = 0 }
        END {
            for (n in want) {
                if (!(n in seen)) {
                    printf("#error \"not found in hypervisor.cpp: %s\"\n", n);
                }
            }
            printf("// extracted %d definitions\n", found);
        }
    ' "$SRC/src/hypervisor/hypervisor.cpp"
    echo '}'
} > real.cpp

EXTRACTED=$(grep -c '^// extracted' real.cpp || true)
if [ "$EXTRACTED" != "1" ]; then
    echo "extraction failed" >&2
    exit 1
fi
grep -q '#error' real.cpp && { grep '#error' real.cpp >&2; exit 1; }
echo "$(sed -n 's/^\/\/ extracted \([0-9]*\) .*/\1/p' real.cpp) definitions extracted"

clang++ -std=c++2c -g -O0 -Wall -Wextra -fno-exceptions -fno-rtti \
    -I shim -I ../nested_vmx/shim -I "$SRC/include" -I . \
    harness.cpp real.cpp -o wpage
exec ./wpage
