// GENERATED by build.sh - do not edit, do not commit.
// The bodies below are cut verbatim out of
// hypervisor/src/hypervisor/hypervisor.cpp.
#include "zpp/hypervisor/hypervisor.h"
namespace zpp::hypervisor {
std::expected<void, zpp::error> hypervisor::watch_guest_page_writes(
    std::uint64_t guest_physical,
    page_watch::handler on_write,
    void * context,
    page_watch::mode behaviour,
    void (*before_write)(void *, std::uint64_t),
    page_watch::filter filter_write)
{
    auto page = guest_physical >> 12;

    // Re-arming the same page replaces the handler rather than taking a
    // second slot, so a caller that cannot easily tell whether it has
    // already armed does not silently exhaust the table.
    page_watch * free_slot{};
    for (auto & watch : this->watches) {
        if (watch.armed && (watch.page == page)) {
            watch.on_write = on_write;
            watch.context = context;
            watch.before_write = before_write;
            watch.filter_write = filter_write;
            watch.behaviour = behaviour;
            return {};
        }
        if (!watch.armed && !free_slot) {
            free_slot = &watch;
        }
    }

    if (!free_slot) {
        return std::unexpected(zpp::error{error::out_of_ept_entries});
    }

    // The EPT is an identity map, so the guest physical address is also
    // the host physical one. Taken through the same call the module
    // protection uses, so a 2 MB entry covering a device register page
    // is split here rather than silently protecting two megabytes of
    // unrelated memory.
    auto entry = epte_for(page << 12);
    if (!entry) {
        return std::unexpected(entry.error());
    }

    // Reads stay permitted. A driver polls status registers far more
    // often than it writes commands, and every permitted read is a VM
    // exit that does not happen.
    (*entry)->write(false);
    invalidate_ept();

    free_slot->page = page;
    free_slot->on_write = on_write;
    free_slot->context = context;
    free_slot->before_write = before_write;
    free_slot->filter_write = filter_write;
    free_slot->behaviour = behaviour;
    free_slot->held.store(false, std::memory_order_relaxed);
    free_slot->armed = true;

    log("watching writes to guest page {}", page);
    return {};
}
void hypervisor::unwatch_guest_page(std::uint64_t guest_physical)
{
    auto page = guest_physical >> 12;

    for (auto & watch : this->watches) {
        if (!watch.armed || (watch.page != page)) {
            continue;
        }

        // The entry exists already - the page was split when the watch
        // was armed - so this cannot fail and nothing here has to cope
        // with it failing.
        if (auto entry = epte_for(page << 12)) {
            (*entry)->write(true);
            invalidate_ept();
        }

        watch.page = {};
        watch.on_write = {};
        watch.context = {};
        watch.behaviour = page_watch::mode::notify;
        watch.held.store(false, std::memory_order_relaxed);
        watch.armed = false;
        log("stopped watching guest page {}", page);
        return;
    }
}
std::optional<std::uint64_t> hypervisor::read_guest_word(
    std::uint64_t guest_physical, std::uint8_t size)
{
    // Straight through the host page table, for the same reason the write
    // below goes that way: the extended page tables establish an identity
    // between guest physical and host physical, and our own mapping of the
    // page is the only one that is not protected.
    auto * at =
        reinterpret_cast<const volatile std::uint8_t *>(guest_physical);

    if (!this->host_page_table.virtual_to_physical(
            reinterpret_cast<const void *>(guest_physical))) {
        return {};
    }

    switch (size) {
    case 1:
        return arch::x86_64::read8(at);
    case 2:
        return arch::x86_64::read16(at);
    case 4:
        return arch::x86_64::read32(at);
    case 8:
        return arch::x86_64::read64(at);
    default:
        return {};
    }
}
bool hypervisor::carry_out_guest_instruction(
    std::uint64_t guest_physical,
    const arch::x86_64::decoded_instruction & instruction,
    arch::x86_64::context & context,
    guest_write & performed,
    bool & changed_memory,
    std::optional<std::uint64_t> known_contents)
{
    using arch::x86_64::memory_operation;

    // A store replaces the contents outright, so the old value is not
    // needed - and must not be demanded, since a device register that
    // reads differently from what was written is exactly the case this
    // exists to observe.
    auto needs_old = (memory_operation::store != instruction.what);

    std::uint64_t old{};
    if (needs_old) {
        // The caller may already have read it, to show the filter what
        // this instruction was going to leave behind. Reading again is
        // not free and not even idempotent: these are device registers,
        // and on the local APIC page a second read is a second access to
        // hardware whose answer may differ from the first - so the two
        // halves of one instruction would combine against different
        // contents. Threaded through rather than re-read.
        if (known_contents) {
            old = *known_contents;
        } else {
            auto read = read_guest_word(guest_physical, instruction.size);
            if (!read) {
                return false;
            }

            old = *read;
        }
    }

    auto replacement = arch::x86_64::apply(instruction, old);

    // Written back only where the instruction actually changes memory. An
    // examine that wrote its own value back would turn a read of a device
    // register into a write of it, which on a register with side effects
    // is a different instruction from the one the guest executed.
    auto writes_memory = (memory_operation::load != instruction.what) &&
                         (memory_operation::examine != instruction.what);

    if (writes_memory) {
        auto stored = arch::x86_64::memory_store{
            .value = replacement,
            .size = instruction.size,
        };

        if (!apply_guest_store(guest_physical, stored)) {
            return false;
        }
    }

    if (instruction.writes_register) {
        auto & slot =
            context.*arch::x86_64::register_of(instruction.destination);
        slot = arch::x86_64::result_for_register(instruction, old, slot);
    }

    // The flags, which are not optional.
    //
    // Every operation here except the moves and the exchange sets them,
    // and the guest branches on them immediately - `and [mem], eax` is
    // followed by a `jz`. Carrying out the arithmetic and leaving RFLAGS
    // alone makes the guest take the other branch, and that is not a
    // subtle corruption: it was measured as a triple fault, exit reason 2,
    // after 179 emulated instructions. The decoder this replaces never
    // needed it because MOV sets no flags.
    if (arch::x86_64::memory_operation::store != instruction.what) {
        this->vmcs.guest_rflags(arch::x86_64::flags_after(
            instruction, this->vmcs.guest_rflags(), old, replacement));
    }

    // What the watch is told. The value reported is what the memory now
    // holds, which for a combine is the combination rather than the
    // operand - a handler looking for "did the guest clear the enable
    // bit" wants the result, not the mask.
    performed = guest_write{
        .address = guest_physical,
        .value = writes_memory ? replacement : old,
        .size = instruction.size,
    };

    changed_memory = writes_memory;

    // Recorded newest-last so the few before a failure can be read out.
    // Everything the emulation decided is here: what it thought the
    // instruction was, the width, what memory held and what it now holds.
    //
    // Only the operations the narrow decoder could not answer are kept.
    // A plain store is not new - it was emulated before this decoder
    // existed and on a build that booted - so recording those fills the
    // ring with traffic that is known good and hides the ones that are
    // not. Freezes when full, because the first of a new kind is what
    // matters.
    if ((memory_operation::store != instruction.what) &&
        (this->emulated_trace_count < emulated_trace_capacity)) {
        auto slot = this->emulated_trace_count;
        auto & recorded = this->emulated_trace[slot];

        for (std::size_t i{}; i < sizeof(recorded.code); ++i) {
            recorded.code[i] = this->last_fetched_code[i];
        }

        recorded.page = guest_physical >> 12;
        recorded.old_value = old;
        recorded.new_value = replacement;
        recorded.what = static_cast<std::uint32_t>(instruction.what);
        recorded.how = static_cast<std::uint32_t>(instruction.how);
        recorded.size = instruction.size;
        recorded.wrote = writes_memory ? 1u : 0u;

        this->emulated_trace_count = this->emulated_trace_count + 1;
    }

    return true;
}
bool hypervisor::apply_guest_store(
    std::uint64_t guest_physical, const arch::x86_64::memory_store & store)
{
    // Straight through the host page table, which is the only mapping of
    // this page that is writable - the guest's own is not, which is the
    // whole point. The identity between guest and host physical that the
    // EPT establishes is what makes the address usable here directly.
    auto * at = static_cast<volatile std::uint8_t *>(
        reinterpret_cast<void *>(guest_physical));

    if (!this->host_page_table.virtual_to_physical(
            reinterpret_cast<const void *>(guest_physical))) {
        return false;
    }

    switch (store.size) {
    case 1:
        arch::x86_64::write8(at, static_cast<std::uint8_t>(store.value));
        return true;
    case 2:
        arch::x86_64::write16(at, static_cast<std::uint16_t>(store.value));
        return true;
    case 4:
        arch::x86_64::write32(at, static_cast<std::uint32_t>(store.value));
        return true;
    case 8:
        arch::x86_64::write64(at, store.value);
        return true;
    default:
        return false;
    }
}
bool hypervisor::on_ept_violation(std::size_t cpu,
                                  arch::x86_64::context & context,
                                  std::uint64_t guest_physical)
{
    auto page = guest_physical >> 12;

    for (auto & watch : this->watches) {
        if (!watch.armed || (watch.page != page)) {
            continue;
        }

        // Last chance to use the controller the guest is about to take
        // away. See page_watch::before_write.
        if (watch.before_write) {
            watch.before_write(watch.context, page);
        }

        // A held page stops the writer here, at the faulting
        // instruction, until whoever is holding it lets go.
        //
        // This is the whole of the exclusion. The write has not taken
        // effect when the violation is delivered, so the page is
        // unchanged for as long as the spin lasts, and a borrower can
        // work on a structure the guest owns without the guest being
        // able to touch it. No cooperation is required and no processor
        // that is not writing this page is delayed at all.
        //
        // Spinning inside the exit is deliberate. The alternative -
        // resuming and re-faulting - burns exits for the same wait and
        // gives the guest a window between the resume and the next
        // fault, which is the window this exists to close.
        while (watch.held.load(std::memory_order_acquire)) {
            zpp::spin_hint();
        }

        // Emulate the write where the instruction can be decoded, and
        // only step over it where it cannot.
        //
        // Stepping over means opening the page, letting one instruction
        // retire and closing it again, and for that window the page is
        // writable *for every processor*. That is not a theoretical
        // hole: a driver writes CC twice in succession, disable then
        // enable, and the second write goes through the window the first
        // opened. Measured - one trapped write of 0x00460000, a
        // controller afterwards reading 0x00460001, and no transition
        // seen. Losing that transition is losing the channel, because a
        // reset is the one event the sink has to notice.
        //
        // Emulating closes the window by never opening it. The page
        // stays unwritable, every write faults, and each is applied by
        // this VMM with the value it decoded - so a second write cannot
        // slip past a first, and the handler is told what was written
        // rather than having to read the register back and race the
        // guest for it.
        // Only a violation caused by the instruction's own operand may
        // be emulated. Bit 8 of the exit qualification clear means the
        // access was to a paging-structure entry - the processor walking
        // the guest's tables - and there is no store in the instruction
        // to carry out for that. SDM Table 28-7.
        constexpr std::uint64_t qualification_linear_address_valid = 1ull
                                                                     << 7;
        constexpr std::uint64_t qualification_operand_access = 1ull << 8;

        auto qualification = this->vmcs.exit_qualification();
        auto reports_linear =
            (0 != (qualification & qualification_linear_address_valid));

        // Decoded up front, because both paths below want it: emulating
        // needs the operation, and *addressing* needs it whenever the
        // exit did not report a linear address.
        auto instruction = decode_guest_instruction(cpu, context);

        auto decoded_address =
            instruction
                ? arch::x86_64::effective_address(
                      *instruction, context, this->vmcs.guest_rip())
                : std::nullopt;

        // Where in the page the access landed, from three sources,
        // strongest first.
        //
        // **The guest-physical address is not one of them, despite being
        // the obvious one.** The processor reports it at *page*
        // granularity for an EPT violation, so its low twelve bits are
        // not the offset the instruction named. Taking them anyway made
        // every access look like an access to offset 0 - a reserved local
        // APIC register - and the interrupt-command handler, which acts
        // only on a write to the command register, could never be reached
        // no matter what the guest wrote.
        //
        // Measured, which is the only reason it was found: twenty-four
        // consecutive accesses recorded as page 0xfee00 offset 0, while
        // the exit ring showed the writes arriving and the handler showed
        // not one call. A guest hypervisor was running with its
        // processors never starting, waiting for start-up interrupts this
        // VMM had received and thrown the register number away from.
        //
        // The guest-linear address the same exit reports would answer it,
        // and does whenever qualification bit 7 is set. It is not always:
        // on the machine where the guest hypervisor runs, *every one* of
        // those violations arrived with bit 7 clear. So the instruction's
        // own addressing bytes are the third source and the only one that
        // does not depend on what the hardware volunteered.
        constexpr std::uint64_t page_offset_mask = page_size - 1;

        auto page_base = guest_physical & ~page_offset_mask;
        auto address = guest_physical;
        auto address_known = reports_linear;

        // Whether the processor - or, on the rig, KVM - answers this
        // question itself. Counted before anything is decided, so the
        // three counters describe every violation rather than the subset
        // that took some branch. See the members for why this is in
        // doubt.
        if (auto physical_offset = guest_physical & page_offset_mask;
            0 != physical_offset) {
            this->physical_offset_present =
                this->physical_offset_present + 1;

            if (reports_linear) {
                if (physical_offset == (this->vmcs.guest_linear_address() &
                                        page_offset_mask)) {
                    this->physical_offset_agreed =
                        this->physical_offset_agreed + 1;
                } else {
                    this->physical_offset_disagreed =
                        this->physical_offset_disagreed + 1;
                }
            }
        }

        if (reports_linear) {
            address = page_base | (this->vmcs.guest_linear_address() &
                                   page_offset_mask);
        } else if (decoded_address) {
            address = page_base | (*decoded_address & page_offset_mask);
            address_known = true;

            this->access_offset_decoded = this->access_offset_decoded + 1;
        } else {
            this->access_offset_unknown = this->access_offset_unknown + 1;
        }

        // Whether the fault was the instruction's own operand rather than
        // the processor walking the guest's paging structures.
        //
        // Bit 8 answers it outright, but only when bit 7 says the exit
        // has a linear address at all. Without it the question is settled
        // instead by *which page* faulted: these are watched pages, and a
        // watched page is a device's registers - the local APIC, a
        // controller's configuration space. No guest puts its paging
        // structures in uncacheable device memory, so an access to one of
        // them is never a table walk.
        auto operand_access =
            reports_linear
                ? (0 != (qualification & qualification_operand_access))
                : address_known;

        if (auto store = (emulate_watched_page_writes && operand_access)
                             ? instruction
                             : std::nullopt) {
            // A store that crosses the end of the watched page would be
            // applied whole at the faulting address, writing bytes onto
            // the page that follows. Refused rather than split: nothing
            // a driver does to a register straddles the page, so the
            // fallback costs nothing and a wrong split would be silent.
            auto offset_in_page = address & page_offset_mask;
            auto straddles = (offset_in_page + store->size) > page_size;

            // The watch gets to refuse the write before it happens.
            //
            // This is where a start-up IPI is caught. Writing the local
            // APIC's command register *is* the send, so a VMM that
            // redirects one has to decide here - after the write there is
            // nothing left to redirect. See page_watch::filter.
            //
            // Every form that writes memory is consulted, not only a
            // plain store. Restricting it to stores was the other half of
            // the bug fixed alongside this: a read-modify-write reached
            // the notify instead, *after* the send, and the notify's
            // handler adopts a start-up IPI by starting the processor
            // itself - so the hardware had the guest's command and this
            // VMM sent a second one. Two start-up IPIs per command is not
            // subtle; the same shape was measured as a triple fault, exit
            // reason 2, after 179 emulated writes to this page.
            //
            // The value a non-store form will leave behind is not in the
            // instruction, so it is computed the way
            // carry_out_guest_instruction computes it - read what is
            // there, apply the operation. A register that reads
            // differently from what was written makes this the wrong
            // question for a *store*, which is why a store still uses its
            // operand and never reads first.
            auto filter_consulted = false;
            auto refused_rewrite = false;

            auto writes_memory =
                (arch::x86_64::memory_operation::load != store->what) &&
                (arch::x86_64::memory_operation::examine != store->what);

            std::optional<std::uint64_t> known_contents;
            std::optional<std::uint64_t> intended_value;
            if (arch::x86_64::memory_operation::store == store->what) {
                intended_value = store->operand;
            } else if (writes_memory) {
                known_contents = read_guest_word(address, store->size);
                if (known_contents) {
                    intended_value =
                        arch::x86_64::apply(*store, *known_contents);
                }
            }

            if (watch.filter_write && !straddles && intended_value) {
                filter_consulted = true;
                guest_write intended{
                    .address = address,
                    .value = *intended_value,
                    .size = store->size,
                };

                auto allowed =
                    watch.filter_write(watch.context, page, &intended);

                if (!allowed) {
                    // Refused. The guest still retires the instruction -
                    // it must, or it re-executes and faults for ever -
                    // but memory and the device are left alone.
                    this->emulated_writes = this->emulated_writes + 1;
                    this->filtered_writes = this->filtered_writes + 1;

                    auto reported =
                        this->vmcs.vm_exit_instruction_length();
                    if ((0 != reported) && (reported != store->length)) {
                        this->emulated_length_disagreement =
                            this->emulated_length_disagreement + 1;
                        this->emulated_length_reported = reported;
                        this->emulated_length_decoded = store->length;
                        return false;
                    }

                    this->vmcs.guest_rip(this->vmcs.guest_rip() +
                                         store->length);
                    return true;
                }

                // Allowed, possibly with a different value.
                //
                // A plain store carries the value in its operand, so
                // replacing it is the whole of the rewrite. Every other
                // form derives what it writes from what is already there,
                // and there is nowhere to put a value the operation would
                // not have produced - so a filter that rewrites one is
                // refused emulation rather than half honoured, and the
                // access takes the stepping path instead.
                //
                // Unreachable today, and deliberately not papered over:
                // the only filter here is the local APIC's, and
                // on_interrupt_command returns the command it was given
                // on every path, so the rewrite never fires. It is the
                // next filter that would find this out.
                if (*allowed != *intended_value) {
                    // A store and an exchange both leave their operand
                    // in memory - `apply` returns it unchanged for
                    // either - so replacing the operand honours the
                    // rewrite exactly. Every other form derives what it
                    // writes from what is already there and has nowhere
                    // to put a value the operation would not have
                    // produced.
                    if ((arch::x86_64::memory_operation::store ==
                         store->what) ||
                        (arch::x86_64::memory_operation::exchange ==
                         store->what)) {
                        auto replaced = *store;
                        replaced.operand = *allowed;
                        store = replaced;
                    } else {
                        // Refused *emulation*, which is not the same as
                        // refusing the access. This used to `return
                        // false`, and the comment above claiming it took
                        // the stepping path was simply wrong: false is
                        // how on_ept_violation says "nothing had this
                        // page watched", and the caller treats that as a
                        // bug here and stops the processor. Letting the
                        // condition below fail is what actually reaches
                        // the stepping path.
                        refused_rewrite = true;
                    }
                }
            }

            guest_write written{};

            auto changed_memory = false;

            if (!straddles && !refused_rewrite &&
                carry_out_guest_instruction(address,
                                            *store,
                                            context,
                                            written,
                                            changed_memory,
                                            known_contents)) {
                // Only an access that actually changed memory is reported.
                //
                // The decoder now answers loads and examinations as well
                // as writes, which is the point of it - but a handler
                // watching a device register is watching for *writes*, and
                // handing it a read would be a different event wearing the
                // same shape. On the local APIC page that is not a
                // subtlety: the interrupt command register's handler acts
                // on a write to it, so reporting a read of it sends an
                // interrupt the guest never asked for. Measured as a guest
                // that never left early boot.
                // Not when the filter answered it. The filter is the
                // handler for an emulated write - it already saw the
                // value, before the write rather after - and calling
                // both would act on one command twice.
                //
                // Whether the filter *ran*, not whether one exists, and
                // that is the whole of this condition. The filter is
                // consulted only for a plain store, so testing for its
                // existence silently dropped every other form that writes
                // memory: a locked read-modify-write against a watched
                // page changed the page and told nobody.
                //
                // That is not a corner. SDM Table 30-7 says an EPT
                // violation from a read-modify-write sets bit 1 and may
                // also set bit 0, and the boot processor's ring on the
                // rig is full of qualification 0x2b against 0xfee00000 -
                // both bits, so a read-modify-write to the local APIC
                // page. Every one of those went past
                // filter_local_apic_write and on_local_apic_write alike,
                // so on_interrupt_command never saw it: no start-up IPI
                // adoption, no broadcast resolution against the roster,
                // and no log line. The write itself still reached the
                // register, which is why this was invisible.
                //
                // KVM does not key APIC emulation on the instruction form
                // at all - apic_mmio_write (lapic.c) gates on width and
                // alignment only, and x86.c:8068 degrades a locked
                // exchange against the APIC page to a plain write so it
                // lands in the same dispatcher.
                if (changed_memory && watch.on_write &&
                    !filter_consulted) {
                    watch.on_write(watch.context, page, &written);
                }

                this->emulated_writes = this->emulated_writes + 1;

                // The instruction has been carried out, so the guest
                // resumes after it rather than on it - by the length the
                // decoder measured, not the one the VMCS reports.
                //
                // SDM 30.2.5 leaves the VM-exit instruction length field
                // *undefined* for an EPT violation that was not
                // encountered during event delivery, and KVM agrees by
                // construction: handle_ept_violation never reads it, and
                // skip_emulated_instruction warns that it is not always
                // set. Advancing by an undefined value resumes the guest
                // somewhere inside its own instruction stream.
                //
                // Where the processor did supply a length and the two
                // disagree, the decoder has misread the instruction, and
                // the value already written to the device register makes
                // that unsafe to paper over. Recorded and the processor
                // stopped, rather than resumed at either address.
                auto reported = this->vmcs.vm_exit_instruction_length();
                if ((0 != reported) && (reported != store->length)) {
                    this->emulated_length_disagreement =
                        this->emulated_length_disagreement + 1;
                    this->emulated_length_reported = reported;
                    this->emulated_length_decoded = store->length;
                    return false;
                }

                this->vmcs.guest_rip(this->vmcs.guest_rip() +
                                     store->length);
                return true;
            }
        }

        // Not a form the decoder handles, so fall back to letting the
        // guest's own instruction do the write. This keeps the window
        // described above, and is why the decoder refusing is a
        // correctness question rather than only a performance one.
        if (auto entry = epte_for(page << 12)) {
            (*entry)->write(true);
            invalidate_ept();
        }

        this->stepped_writes = this->stepped_writes + 1;

        this->stepping_watch[cpu] = true;
        this->stepping_page[cpu] = page;

        // The address resolved above, whichever of the three sources
        // answered it. Reaching here means the instruction could not be
        // carried out, not that the address is unknown.
        this->stepping_offset[cpu] = address & page_offset_mask;

        // Where the guest is now, so the trap exit can tell whether the
        // instruction retired. See stepping_rip.
        this->stepping_rip[cpu] = this->vmcs.guest_rip();
        monitor_trap_flag(true);
        return true;
    }

    // Not a watched page. It may still be one of ours: protect_module
    // makes every page of this module not-present to the guest, so any
    // access to them arrives here.
    //
    // Stopping the processor for that would be a poor trade. A guest is
    // entitled to walk physical memory - a memory manager building its
    // own map does exactly that - and killing it for reading an address
    // it has no idea is special turns a curiosity into a bug check.
    //
    // So the page is redirected, permanently, to a page of zeroes. The
    // guest is resumed **without** advancing past its own instruction,
    // which then re-executes and completes against the decoy. That needs
    // no decoder, cannot disagree with what the instruction meant, and
    // costs one exit per module page ever touched rather than one per
    // access - a guest scanning memory pays once per page and then runs
    // at full speed through a region that tells it nothing.
    if (this->module_physical_to_virtual.find(page << 12) !=
        this->module_physical_to_virtual.end()) {
        ++this->module_access_count;

        diag::log<diag::severity::warning>(
            "guest touched module memory at {} from rip {}, {} pages so "
            "far",
            guest_physical,
            this->vmcs.guest_rip(),
            this->module_access_count);
        log("guest touched module memory at {} from rip {}",
            guest_physical,
            this->vmcs.guest_rip());

        if (auto entry = epte_for(page << 12)) {
            (*entry)->page_number(
                this->host_page_table.virtual_to_physical(
                    this->unprotected_memory.decoy_page) >>
                12);

            // Executable as well as readable, deliberately. If the guest
            // jumps into this it should run zeroes and reach whatever
            // conclusion that leads to, rather than fault here forever
            // on a page it is allowed to touch.
            (*entry)->read(true);
            (*entry)->write(true);
            (*entry)->execute(true);
            (*entry)->execute_user(true);
            invalidate_ept();
        }

        return true;
    }

    return false;
}
bool hypervisor::on_monitor_trap_flag(std::size_t cpu)
{
    if (!this->stepping_watch[cpu]) {
        return false;
    }

    auto page = this->stepping_page[cpu];
    auto offset = this->stepping_offset[cpu];
    auto armed_at = this->stepping_rip[cpu];
    this->stepping_watch[cpu] = false;
    this->stepping_page[cpu] = {};
    this->stepping_offset[cpu] = {};
    this->stepping_rip[cpu] = {};
    monitor_trap_flag(false);

    // Close the page again before the handler runs, so that a handler
    // which arms or disarms watches cannot observe a half open state.
    if (auto entry = epte_for(page << 12)) {
        (*entry)->write(false);
        invalidate_ept();
    }

    // Whether the instruction actually ran.
    //
    // A monitor-trap-flag exit does not say that it did. SDM 26.5.2
    // (.references/sdm.txt:201495): "If the instruction causes a fault,
    // an MTF VM exit is pending on the instruction boundary following
    // delivery of the fault (or any nested exception)", and the case
    // above it is the same for a pending event delivered before the
    // instruction can execute. In both the guest's write has not
    // happened and RIP is inside a handler, not past the instruction.
    //
    // An instruction that retired left RIP between one and fifteen bytes
    // on - fifteen being the architectural maximum length - and it
    // cannot have branched, because the only forms stepped here are the
    // ones that faulted writing a watched page. Anything else means a
    // handler was entered instead.
    //
    // Reporting nothing is the safe answer, because the alternative is
    // reporting a write that never happened: on the local APIC page that
    // hands on_interrupt_command a stale command register, which can
    // adopt a start-up IPI nobody sent. Counted, so that writes being
    // missed this way is visible rather than silent.
    //
    // Also bounded to the page. The read below is four bytes, and an
    // access resolved to the last three bytes of the page would read
    // past the end of the very page the emulation refused to straddle.
    constexpr std::uint64_t maximum_instruction_length = 15;
    constexpr std::uint64_t page_offset_mask = page_size - 1;

    auto advanced = this->vmcs.guest_rip() - armed_at;
    auto retired =
        (0 != advanced) && (advanced <= maximum_instruction_length);
    auto within_page = offset <= ((page_offset_mask + 1) - 4);

    if (!retired || !within_page) {
        this->stepped_not_retired = this->stepped_not_retired + 1;
        return true;
    }

    // What the step accomplished, in the shape an emulated write arrives
    // in. The step has already run, so the page holds what the guest
    // wrote and the value can simply be read back; the address comes from
    // the exit, which reported it before the step was armed.
    //
    // **Passing nullptr here is what wedged the guest.** A handler given
    // a page and no register cannot act, so every command that arrived
    // this way was dropped - measured as 149 dropped against 178
    // emulated, with the decoder refusing none of them, so these are not
    // a decoder gap and no amount of decoder coverage would have reached
    // them. The guest's start-up IPIs were among the dropped, no
    // application processor started, and the firmware waited for them for
    // ever in EDK2's MpInitLib. The guest never left firmware.
    //
    // Four bytes because every register on the pages watched here is a
    // dword, and the width is not reported by the exit.
    if (auto slot = this->watched_access_count;
        slot < watched_access_capacity) {
        this->watched_accesses[slot] = watched_access{
            .page = page,
            .offset = offset,
        };

        this->watched_access_count = slot + 1;
    }

    auto stepped = guest_write{
        .address = (page << 12) | offset,
        .value =
            arch::x86_64::read32(reinterpret_cast<volatile std::uint8_t *>(
                (page << 12) | offset)),
        .size = 4,
    };

    for (auto & watch : this->watches) {
        if (watch.armed && (watch.page == page) && watch.on_write) {
            watch.on_write(watch.context, page, &stepped);
            break;
        }
    }

    return true;
}
std::optional<std::uint64_t> hypervisor::filter_local_apic_write(
    void * context, std::uint64_t page, const guest_write * write)
{
    auto & self = *static_cast<hypervisor *>(context);

    if (!write) {
        return {};
    }

    // Writing the low half is what sends the command. Every other
    // register on the page - the end of interrupt, the task priority, the
    // destination half at 0x310 - is left exactly alone.
    constexpr std::uint64_t interrupt_command_low = 0x300;
    constexpr std::uint64_t interrupt_command_high = 0x310;
    constexpr std::uint64_t page_offset_mask = page_size - 1;

    // Only a 4-byte access on a 16-byte boundary is a register access at
    // all, and anything else is passed through without being read as a
    // command.
    //
    // SDM 13.4.1 (.references/sdm.txt:170419): "Registers are 32 bits,
    // 64 bits, or 256 bits in width; all are aligned on 128-bit
    // boundaries. All 32-bit registers should be accessed using 128-bit
    // aligned 32-bit loads or stores ... any access that touches bytes 4
    // through 15 of an APIC register may cause undefined behavior".
    // KVM's apic_mmio_write (lapic.c) opens with exactly this test -
    // `if (len != 4 || (offset & 0xf)) return 0;` - and drops the write.
    //
    // Without it the command register was composed from whatever a
    // narrow or misaligned access happened to carry. `mov byte [apic +
    // 0x300], 0x11` composed 0x0000000200000011 and **sent an interrupt
    // the guest never wrote** - vector from the one byte, delivery mode,
    // level and shorthand all zero, destination from a register the
    // guest was not writing. A four-byte write at offset 0x2fe put two
    // of its bytes into the command register while the filter was asked
    // about offset 0x2fe and saw nothing.
    //
    // The write itself is still performed: this page is the processor's
    // real local APIC, so what a narrow store does to it is the
    // hardware's business and the same thing would happen without a VMM
    // in the way. What is refused is *interpreting* it as a command.
    constexpr std::uint64_t register_size = 4;
    constexpr std::uint64_t register_alignment_mask = 0xf;

    if ((register_size != write->size) ||
        (0 != (write->address & register_alignment_mask))) {
        return write->value;
    }

    if (interrupt_command_low != (write->address & page_offset_mask)) {
        auto offset = write->address & page_offset_mask;

        // Which register, for the writes this hook deliberately passes
        // through. A wedged guest hypervisor writing the page twice every
        // few seconds is doing something with it, and "not the interrupt
        // command register" is all this used to be able to say. Collapsed
        // by the log the same way as everything else, so a register
        // written in a loop with one value costs one line.
        //
        // Three registers are excluded, and "twice every few seconds" is
        // exactly the assumption that turned out to be wrong about them.
        // Measured on the rig: an idle Hyper-V writes the timer's initial
        // count and then the end of interrupt once per tick, at about ten
        // thousand a second on the boot processor alone - 1.25 million
        // exits in one run, the whole of that processor's exit ring, two
        // alternating RIPs. Every one took the global log lock and
        // allocated a line whose only content was a counter value that
        // never repeats, so the deduplication could not collapse them
        // either. The dominant cost of an interrupt on this machine was
        // this diagnostic.
        //
        // They are excluded rather than the log being made cheaper
        // because none of the three says anything: the end of interrupt
        // carries no value, the task priority is not consulted here, and
        // the initial count is a deadline whose *rate* is the interesting
        // thing and is better read from the exit ring. Everything a guest
        // writes once - the LVTs, the destination format, the spurious
        // vector - still logs, which is what this was added to see.
        constexpr std::uint64_t end_of_interrupt = 0xb0;
        constexpr std::uint64_t task_priority = 0x80;
        constexpr std::uint64_t timer_initial_count = 0x380;

        if ((end_of_interrupt != offset) && (task_priority != offset) &&
            (timer_initial_count != offset)) {
            log("guest apic write, register {}, value {}",
                offset,
                write->value);
        }

        // The two registers that decide what an initial count *means*,
        // remembered so the count can be recorded with them rather than
        // on its own. A count says nothing by itself: 0x320 carries the
        // mask bit, the mode - one-shot, periodic or TSC deadline - and
        // the vector, and 0x3e0 carries the divisor the count is scaled
        // by. Measured on the rig, the guest hypervisor uses all of it:
        // it starts periodic at vector 5 and then switches to one-shot at
        // vector 0xef with divide-by-one, arming and disarming once per
        // processor it brings up. A ring of bare counts recorded across
        // that switch would be two different quantities in one column.
        constexpr std::uint64_t lvt_timer = 0x320;
        constexpr std::uint64_t divide_configuration = 0x3e0;

        if (auto cpu = self.vmcs.vpid() - 1; cpu < max_cpus) {
            if (lvt_timer == offset) {
                self.timer_lvt[cpu] = write->value;
            } else if (divide_configuration == offset) {
                self.timer_divide[cpu] = write->value;
            }
        }

        // The initial count is excluded from the log above and recorded
        // here instead, in a fixed per-processor array that keeps the
        // *earliest* writes rather than the latest.
        //
        // Both halves of that matter. It cannot go in the log because it
        // is the hottest write on the page and no two values repeat, so
        // the deduplication that makes the log affordable does nothing
        // for it and a boot's worth would evict everything else. And it
        // must keep the earliest writes because the calibration is the
        // first thing a guest does with this register - a ring would hold
        // the millionth arming and throw away the one that decided it.
        //
        // The time stamp is what makes the values mean anything. A
        // calibration is an arm, a wait and a read back, so the real time
        // between two armings separates a guest that measured a true
        // interval and scaled it wrongly from one that measured an
        // interval this VMM had already stretched. Measured on the rig:
        // this guest arms to about 2.38e9 where the same guest with
        // nothing underneath arms to 1,961,755.
        if (timer_initial_count == offset) {
            if (auto cpu = self.vmcs.vpid() - 1; cpu < max_cpus) {
                if (auto slot = self.timer_arm_count[cpu];
                    slot < timer_arm_capacity) {
                    self.timer_arm_value[cpu][slot] = write->value;
                    self.timer_arm_tsc[cpu][slot] = arch::x86_64::rdtsc();
                    self.timer_arm_count[cpu] = slot + 1;
                }

                // And the newest, in a ring, which is a different
                // question from the one the array above answers.
                //
                // That one holds the calibration and must not be evicted
                // by it. This one holds the last deadline the guest
                // hypervisor programmed before the machine stopped, and
                // the stop is at the end - so the array above is
                // guaranteed to have been full for minutes by the time
                // anything interesting happens, and reading it after a
                // freeze shows the first thirty-two armings of a boot
                // whose last thirty-two are the ones being asked about.
                //
                // Recorded with the mode and divisor as they stood, since
                // a count is meaningless without them.
                auto slot =
                    self.timer_arm_recent_count[cpu] % timer_arm_capacity;
                self.timer_arm_recent_value[cpu][slot] = write->value;
                self.timer_arm_recent_tsc[cpu][slot] =
                    arch::x86_64::rdtsc();
                self.timer_arm_recent_lvt[cpu][slot] = self.timer_lvt[cpu];
                self.timer_arm_recent_divide[cpu][slot] =
                    self.timer_divide[cpu];
                self.timer_arm_recent_count[cpu] =
                    self.timer_arm_recent_count[cpu] + 1;
            }
        }

        return write->value;
    }

    // The destination half, which the guest wrote first - it has to, for
    // the same reason this hook exists - so it is already in the page and
    // is read from there rather than remembered.
    //
    // Composed into the x2APIC shape, destination in bits 63:32, so the
    // one decision function serves both forms. The xAPIC destination is
    // eight bits in 31:24 of that dword.
    auto * bytes = reinterpret_cast<volatile std::uint8_t *>(page << 12);
    auto high = arch::x86_64::read32(bytes + interrupt_command_high);

    auto command = (write->value & 0xffffffffull) |
                   (static_cast<std::uint64_t>(high >> 24) << 32);

    self.apic_page_commands_filtered =
        self.apic_page_commands_filtered + 1;

    // Nothing means this VMM answered the command itself and the guest's
    // write must not go out. A value means it did not, and the guest's
    // own command goes to the hardware unchanged.
    if (!self.on_interrupt_command(command)) {
        return {};
    }

    return write->value;
}
void hypervisor::on_local_apic_write(void * context,
                                     std::uint64_t page,
                                     const hypervisor::guest_write * write)
{
    auto & self = *static_cast<hypervisor *>(context);

    // The write has already happened - the watch steps over it before
    // saying so - which is why the command can simply be read back out
    // of the page rather than decoded from the instruction.
    //
    // The xAPIC form is two dwords rather than one quadword: the low
    // half at 0x300, and the destination in the top eight bits of the
    // dword at 0x310. Composed here into the same shape the x2APIC path
    // produces, so one decision function serves both.
    constexpr std::uint64_t interrupt_command_low = 0x300;
    constexpr std::uint64_t interrupt_command_high = 0x310;

    auto * bytes = reinterpret_cast<volatile std::uint8_t *>(page << 12);
    auto low = arch::x86_64::read32(bytes + interrupt_command_low);
    auto high = arch::x86_64::read32(bytes + interrupt_command_high);

    // Which register was written, taken from the faulting address rather
    // than guessed from the register's contents.
    //
    // **This gate used to test delivery status, and that made the whole
    // path dead.** Bit 12 of the interrupt command register is Delivery
    // Status and it is *read only*: SDM 12.6.1 describes it as "Delivery
    // Status (Read Only)", with 0 meaning either no activity for this
    // source *or* that the previous interrupt from it "was delivered to
    // the processor core and accepted". Software cannot set it, so it was
    // never a marker for "software wrote a command".
    //
    // And by the time this handler runs the send has completed: the write
    // faults, the processor exits, the store is emulated, and only then is
    // the watch's handler called - hundreds of cycles after a delivery
    // that takes a handful. So the bit reads 0, the test refused every
    // write, and `on_interrupt_command` was never reached for an xAPIC
    // command. Measured: zero application processors adopted, seven left
    // in the firmware's own wait loop, and not one line in the log -
    // which the comment a few lines below correctly warns is the
    // indistinguishable case.
    //
    // KVM makes the same point from the other side: it clears the busy bit
    // on every guest write to this register, and its IPI decoder opens by
    // asserting the bit is never set by then - see `kvm_apic_send_ipi` and
    // the write path around it in arch/x86/kvm/lapic.c.
    //
    // Keying on the offset is exact. Writing the low half is what sends
    // the command, so this fires once per command and never on an end of
    // interrupt, which is the traffic the old test was trying to exclude.
    // Stepped rather than emulated, so which register was written is not
    // known - but the command is, because it is read from the page above
    // rather than from the instruction.
    //
    // **Returning here threw away every command that arrived this way,
    // and that was the wedge.** Measured on the rig with a hypervisor
    // announced to the guest: 178 writes to this page emulated and 149
    // stepped, with the decoder refusing *none* of them - so the stepped
    // ones are not a decoder gap, they are accesses the exit
    // qualification did not describe as an operand access, and no decoder
    // would have recovered them. The guest's start-up IPIs were among
    // them, no application processor ever started, and the firmware sat
    // in its own wait loop for them for ever: EDK2's MpInitLib blocks in
    // WaitApWakeup on a per-processor semaphore. The guest was stopped in
    // firmware, RIP unchanged across samples minutes apart, having never
    // reached the operating system.
    //
    // So the value is used and the offset is replaced by a weaker test
    // that this path can actually make: the interrupt command register
    // holding something other than what it last held. Any other register
    // on the page leaves it alone, so unchanged means "not this one".
    if (!write) {
        // Nothing at all is known about the access, which should no
        // longer happen: both the emulated and the stepped path now
        // report an address. Counted rather than guessed at, because
        // acting on the wrong register sends an interrupt nobody asked
        // for.
        self.apic_writes_undecoded = self.apic_writes_undecoded + 1;
        return;
    }

    // The destination alone sends nothing, so there is nothing to decide
    // until the low half follows it.
    auto offset = write->address & (page_size - 1);
    if (interrupt_command_low != offset) {
        return;
    }

    auto command = std::uint64_t{low} | (std::uint64_t{high >> 24} << 32);

    if (auto issue = self.on_interrupt_command(command)) {
        // Only where the handler changed it.
        //
        // **The write has already gone out.** The watch calls this after
        // the store has taken effect - emulated through this VMM's own
        // mapping of the page, which is the real interrupt command
        // register - so the command the guest wrote has already been
        // issued by the time this runs. Re-writing an unchanged value
        // sends it a second time, and two INITs or two start-up IPIs per
        // command is not a subtle fault: it was measured as a triple
        // fault, exit reason 2, after 179 emulated writes to this page.
        //
        // That did not happen while these writes were stepped rather than
        // emulated, because a stepped write arrives here undecoded and is
        // refused above - so the second send is new, and belongs to the
        // emulation.
        //
        // What this does not fix, and is recorded rather than hidden: a
        // handler that decides to *swallow* a command is too late, because
        // the send already happened. Swallowing needs the decision made
        // before the store is applied - `page_watch::before_write` is the
        // hook for it - and the x2APIC path next door is already the right
        // shape, deciding before it executes the write.
        if (*issue == command) {
            return;
        }

        // Put back what the handler decided, in the form this interface
        // takes. The high half is written first, because writing the low
        // half is what sends it.
        arch::x86_64::write32(
            bytes + interrupt_command_high,
            static_cast<std::uint32_t>((*issue >> 32) << 24));
        arch::x86_64::write32(bytes + interrupt_command_low,
                              static_cast<std::uint32_t>(*issue));
    }
}
// extracted 9 definitions
}
