#!/bin/sh
# Differential harness for the nested VMX state machine.
#
#   shim/            stand-ins for hypervisor.h, diag/log.h and the two
#                    asm.h headers, so the REAL nested_vmx.cpp and the REAL
#                    vmcs12.h compile natively on arm64 macOS.
#   harness.cpp      the fake guest memory, the fake VMCS and the tests.
#   fields.inc       every encoding in vmcs_fields.h, generated by:
#                      python3 -c "import re;..."  (see below)
#
# Regenerate fields.inc after editing vmcs_fields.h:
#   python3 - <<'EOF'
#   import re
#   src = open(SRC + '/zpp/arch/x86_64/vmx/vmcs_fields.h').read()
#   body = src.split('{',2)[2]
#   print('\n'.join('    {"%s", %s},' % m.groups()
#         for m in re.finditer(r'^\s*(\w+)\s*=\s*(0x[0-9a-fA-F]+),', body, re.M)))
#   EOF
set -e
cd "$(dirname "$0")"
SRC=${SRC:-"$(cd ../.. && pwd)/hypervisor"}
clang++ -std=c++2c -g -O0 -fno-exceptions -fno-rtti -DZPP_NESTED_VMX=1 \
    -I shim -I "$SRC/include" -I . \
    harness.cpp "$SRC/src/hypervisor/nested_vmx.cpp" -o nvmx
exec ./nvmx
